### PR TITLE
Bsscca

### PR DESCRIPTION
**Pull request by schoffelen**
I have cleaned up the stuff related to bsscca + implemented some new functionality for this method

### CODE REVIEW

**Comment by robertoostenveld** [comment]
could you add it to one of the test scripts? Or make a new test script "test_pull348.m"?

**Comment by robertoostenveld** [comment]
... I realize that a test script will fail due to "external/cellfunction" missing. Do you want to add that as well, or include it in private?

**Comment by schoffelen** [comment]
OK, zoiets?

**Comment by robertoostenveld** [comment]
"made small fix" --> duim omhoog!

**Pull request merged**
