### PR TITLE
Fixes read of Nervus data with mixed sampling rates

### PR DESCRIPTION
**Pull request by robertoostenveld**
This replaces pull request #302 

I checked out "master" from @janbrogger, which contains the changes, rebased it on the fieldtrip master, and subsequently cherry picked all commits onto a new (issue302) branch, except for the last. The last commit contains a zip file, which should not be added to the repository or the repository history. 

The rebasing ensures that the sequence of commits can be merged without conflicts.

### CODE REVIEW

**Comment by janbrogger** [comment]
Thanks!

**Comment by robertoostenveld** [comment]
I tried running the test script, but it does not work with the first test file. On line 499 in private/read_nervus_header.m  it does 

```
nrIdx = fread(h,2, 'uint32');  %783
```
 
and then starts looping forever, since 

```
K>> nrIdx(2)
ans =
   1.1744e+09
```

**Comment by robertoostenveld** [comment]
for the 2nd file ft_read_header works, but ft_read_event fails. The field `hdr.orig.Events(i).date` is missing.

**Comment by robertoostenveld** [comment]
This clearly still needs more work before it can be merged into FieldTrip. 

Regretfully you implemented it on the master branch of your fieldtrip repository. That makes it more difficult now to continue developing without (again) causing all sorts of conflicts to the code (since I did your accept your changes yet, your master is not in sync with the official master). You might have to make a new fork and a new clone of fieldtrip to continue working on this. 

Please take the branch robertoostenveld:issue302-nervus as starting point and make changes to the code so that the test script (which by itself looks just fine) completely works. Then send me the changes as pull request against my branch robertoostenveld:issue302-nervus. I will then test again, and once the test script works, I will merge.

**Comment by janbrogger** [comment]
1. The errors you are getting are the errors I saw when I started looking at this in 2015-6. You must have tested against an old code base. Please try again? (see below)
2. I didn't see any branches in the [fieldtrip/fieldtrip repo](https://github.com/fieldtrip/fieldtrip) except master. I didn't know you used [your own repo](https://github.com/robertoostenveld/fieldtrip/) for branches. Sorry for that. I hope you can take my pull request into your repo, then into the main repo.
3. I forked your repo, fixed one issue to get the test script running (and minor refactoring). If you check out [my repo](https://github.com/janbrogger/fieldtrip) or [look at my pull request on your repo](https://github.com/robertoostenveld/fieldtrip/pull/6), then the test script should run. The test scripts run on two separate computers.

`git checkout https://github.com/janbrogger/fieldtrip fieldtrip_brogger`
Then in matlab (with the Nicolet test data in the right DCCN test subdirectory)
`cd <fieldtrip-brogger-path>
ft_defaults
cd test
test_nicolet-reading`

**Comment by janbrogger** [comment]
This pull request can be deleted. A new better one is in place: https://github.com/robertoostenveld/fieldtrip/pull/8/files

**Comment by schoffelen** [comment]
This PR has been replaced by #1358

**Pull request closed without merging**
