### PR TITLE
Correct a channel label in easycapM1_neighb.mat

### PR DESCRIPTION
**Pull request by rq-Chen**
The channel PO8 was incorrectly labeled as PO6 in the original `easycapM1_neighb.mat`, inconsistent with `easycapM1.mat`.

`ft_neighbourplot(cfg)` with `cfg.method = 'template'; cfg.layout = 'easycapM1.mat'; cfg.template = 'easycapM1_neighb.mat';` would give a figure like this:

Original

I changed all `'PO6'` to `'PO8'` in the `label` and `neighblabel` fields and now it's correct:

New

### CODE REVIEW

**Comment by schoffelen** [comment]
Indeed, it seems that the corresponding layout contains the label PO8, rather than PO6. This seems to be consistent with the documentation from easycap.

**Comment by schoffelen** [comment]
Thanks, I will merge this so that I can test it. Seems OK

**Comment by rq-Chen** [comment]
You're welcome.

**Comment by schoffelen** [comment]
And apologies for taking us so long.

**Comment by schoffelen** [comment]
Note that PRs get merged into the master branch, and will only move to the release branch if our nightly run batch of test functions runs through smoothly. This may occasionally go wrong due to other changes to the code, so it could take a little bit of time before the change will become visible to all.

**Comment by rq-Chen** [comment]
No problem! And thank you for the useful toolbox!

**Pull request merged**
