### PR TITLE
ENH - allow ft_channelrepair to deal with neighboring bad channels

### PR DESCRIPTION
**Pull request by robertoostenveld**
@NataschaRoos and I came across the situation that we want to identify some bad channels in some trials, i.e. in a sparse way, where certain channels in certain trials are replaced by nans. Subsequently we want to interpolate them.

The interpolation goes like this:

```
for i=1:numel(data_bad.trial)
  cfg = [];
  cfg.trials = i;
  cfg.badchannel = []; % this will be autodetected based on nans
  data_repaired_singletrial{i} = ft_channelrepair(cfg, data_bad);
end

data_repaired = ft_appenddata([], data_repaired_singletrial{:});
```

However, we came across the situation that bad channels are neighbours. This pull request updates ft_channelrepair such that bad and missing channels are removed from the `cfg.neighbours` definition prior to interpolating.

### CODE REVIEW

**Comment by robertoostenveld** [comment]
@schoffelen could you please review this?

**Comment by schoffelen** [comment]
BTW quick side thought here, without having looked at the code: with multiple trials, it could be that this strategy really blows up the cfg.previous. Is this something to keep an eye on?

**Comment by robertoostenveld** [comment]
good point, `data_repaired.cfg.previous` would indeed be very large. Better would be to do

```
cfg = [];
cfg.keepprevious = 'no';
data_repaired = ft_appenddata(cfg, data_repaired_singletrial{:});
```

which is using an option that I recently added, also to `ft_defaults`

**Review by schoffelen — APPROVED** [review]
Looks good to me. I caught a typo in the docstring

**Pull request merged**
