### PR TITLE
FIX - in some cases .inside was still created as double

### PR DESCRIPTION
**Pull request by jens-k**
...instead of logicals. This lead to an error later on.

### CODE REVIEW

**Comment by schoffelen** [comment]
Would you mind writing a little test function (and committing it to fieldtrip/test/...) that would reproduce this, had you not fixed it? E.g. you can call it test_pull360

**Comment by jens-k** [comment]
I added a test_pull360.m to this branch.

**Comment by schoffelen** [comment]
Great thanks! almost there :o)
Convention has it that the test 'scripts' are actually functions, which start like

function test_pull360

% TEST test_pull_360
% TEST ft_prepare_sourcemodel

% WALLTIME 00:10:00
% MEM 500mb

++++++++++++++
The lines starting with % are needed to tell torque what resources are needed to run this function, and the lines starting with % TEST serve to automatically trigger a run of this test function once somebody commits a change in the functions mentioned

**Comment by jens-k** [comment]
Mmmh, now maybe?

**Comment by schoffelen** [comment]
:1st_place_medal:

**Comment by schoffelen** [comment]
Thanks!

**Pull request merged**
