### PR TITLE
FIX - robustified texture refinement of structure io images

### PR DESCRIPTION
**Pull request by schoffelen**
placeholder PR, file changes created locally on laptop, I'll pull this first into my repo on the filesystem to do some additional tests, and will upload the test data

### CODE REVIEW

**Comment by schoffelen** [comment]
OK, I added some test files to the filesystem, and a test function that ensures that they can be read in without problems. This includes also 2 reported-to-be-problematic ones by @ssanchezalonso . Sara, this PR fixes your problem. Once all tests succeed on our end, the changes will end up in the newest release version of the toolbox. Otherwise, you could use the 'master branch' to get direct access, if you're impatient.

**Comment by ssanchezalonso** [comment]
Hi Jan-Mathjis,

Thanks so much for your feedback and rapid turnaround. I can load the scans now, but I get the following error:

'cortex_light' is not found in the current folder or on the MATLAB path, but exists in:
    /Users/ssanchezalonso/fieldtrip-20210709/plotting

Change the MATLAB current folder or add its folder to the MATLAB path.

Error in ft_plot_mesh (line 196)
  facecolor = eval(facecolor);

The file is on the MATLAB path. I have tried restarting MATLAB, rehashing the path, changing the current folder, and adding the folder to the MATLAB path. Neither of these solves the problem, so I wonder whether it may not have to do with the file being in the actual path, but rather with some of the changes that were implemented in the ft-plot_mesh script. If I go back to the prior releases, I don’t get this error. Any ideas about what the issue may be?

Thanks,
Sara



From: Jan-Mathijs Schoffelen ***@***.***>
Reply-To: fieldtrip/fieldtrip ***@***.***>
Date: Thursday, July 8, 2021 at 11:10 AM
To: fieldtrip/fieldtrip ***@***.***>
Cc: "Sanchez-alonso, Sara" ***@***.***>, Mention ***@***.***>
Subject: Re: [fieldtrip/fieldtrip] FIX - robustified texture refinement of structure io images (#1826)


OK, I added some test files to the filesystem, and a test function that ensures that they can be read in without problems. This includes also 2 reported-to-be-problematic ones by @ssanchezalonso<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fssanchezalonso&data=04%7C01%7Csara.sanchez.alonso%40yale.edu%7C393b9ca69a6f4d53ff1f08d942228a73%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637613538383405150%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Lquo28yLGzog3%2BWL4ydZ2BWGbfEEph%2BYM7%2BigmxoF4s%3D&reserved=0> . Sara, this PR fixes your problem. Once all tests succeed on our end, the changes will end up in the newest release version of the toolbox. Otherwise, you could use the 'master branch' to get direct access, if you're impatient.

**Comment by robertoostenveld** [comment]
Oh, that must be an error due to a change in color handling that I introduced last week. The bug is not related, but should be squashed. I'll make a separate issue out of this.

**Comment by ssanchezalonso** [comment]
Thanks, Robert. Did you get a chance to make any edits to the script? If so, I can download the latest release and give it a try.

From: Robert Oostenveld ***@***.***>
Reply-To: fieldtrip/fieldtrip ***@***.***>
Date: Sunday, July 11, 2021 at 7:41 AM
To: fieldtrip/fieldtrip ***@***.***>
Cc: "Sanchez-alonso, Sara" ***@***.***>, Mention ***@***.***>
Subject: Re: [fieldtrip/fieldtrip] FIX - robustified texture refinement of structure io images (#1826)


Oh, that must be an error due to a change in color handling that I introduced last week. The bug is not related, but should be squashed. I'll make a separate issue out of this.

**Comment by robertoostenveld** [comment]
Please see #1831. I was not able to reproduce the problem. It might be related to your specific operating system and MATLAB version, please report them in that issue.

**Comment by ssanchezalonso** [comment]
Thanks, Robert. I just saw the issue.

From: Robert Oostenveld ***@***.***>
Reply-To: fieldtrip/fieldtrip ***@***.***>
Date: Monday, July 12, 2021 at 8:47 AM
To: fieldtrip/fieldtrip ***@***.***>
Cc: "Sanchez-alonso, Sara" ***@***.***>, Mention ***@***.***>
Subject: Re: [fieldtrip/fieldtrip] FIX - robustified texture refinement of structure io images (#1826)


Please see #1831<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffieldtrip%2Ffieldtrip%2Fissues%2F1831&data=04%7C01%7Csara.sanchez.alonso%40yale.edu%7C706365e1bdb84d5b9ab208d945333ba8%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637616908621875736%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=RVpA13PvotuCW8JqZIReFKrUt7rlERTfAmp5jQ%2FGOzI%3D&reserved=0>. I was not able to reproduce the problem. It might be related to your specific operating system and MATLAB version, please report them in that issue.

**Pull request merged**
