### PR TITLE
Bug3193

### PR DESCRIPTION
**Pull request by schoffelen**

### CODE REVIEW

**Comment by schoffelen** [comment]
@dieloz could you have a quick look at this please. I have cleaned up the code, to better reflect the current way of defining defaults etc. A quick test on some local data seems to perform well, but I am a bit reluctant to spend too much time in testing. Could I make you my partner in crime to quickly review this, and let the user base take care of the beta testing. As mentioned before, we intend to move away from these dedicated set of defined defaults and would encourage the users to use ft_artifact_zvalue directly

**Comment by dieloz** [comment]
No problem! but I'll do it tomorrow (I'm travelling right now)

**Comment by dieloz** [comment]
I made tests (lastest FT version) with tutorial data and everything went fine. Feel free to merge! Thanks for your help

**Comment by schoffelen** [comment]
thanks

**Pull request merged**
