### PR TITLE
reimplemented the core of the 6 primary plotting functions 

### PR DESCRIPTION
**Pull request by robertoostenveld**
see http://bugzilla.fieldtriptoolbox.org/show_bug.cgi?id=3345

### CODE REVIEW

**Comment by robertoostenveld** [comment]
The end-user help of the functions should be reviewed. 

topoplot_common could use some additional work. 

Also the style of commenting in all plotting functions should be made more consistent (which makes it faster to recognize identical sections).

**Comment by robertoostenveld** [comment]
It now needs independent review. I have been looking at this code too long and am not so good in judging it any more.

The section on connectivity should also be reviewed carefully.

**Comment by robertoostenveld** [comment]
@roemervandermeij, if you want to have a look at the changes that I have been making...

**Comment by schoffelen** [comment]
status update:

- I read through most of the code for the topo functions (multi and single still to be done): this looks good and quite clean so far.
- I fixed some small issues in bivariate_common, and added a startsWith helper function in compat/matlablt2016b

**Comment by roemervandermeij** [comment]
Oh wow Robert, that is quite the massive overhaul. And an impressive reduction: +1491 −2349 ;). Is there anything I can help with? JM, would you like a second viewer? I can make some time for this the coming week. 
I also see there's been some more modularization with the common functions (chanscale, bivariate), very nice. Ugh, so many full time projects I would like to have done for fieldtrip (full databrowser reimplementation, plotting restructuring, etc etc)!...

**Comment by schoffelen** [comment]
By all means, Roemer! I  have been committing a few small fixes (seem to have been adequately pushed to the current PR branch), and I want to test a few more things:
-channel type specific scaling
-on the fly preprocessing
-baseline correction
I hope to be able to work on this today (22 sept). Early next week I will be travelling, so it's safe to review and tamper with the code, if needed, without interfering with each other

**Comment by schoffelen** [comment]
I think we should aim at merging this at the latest end of next week (i.e. september 28)

**Comment by roemervandermeij** [comment]
Alright! I'll look through the code in general, and so some aggressive testing, maybe think of some (future) modularization now that they're all aligned so nicely. I'll probably chime back in mid-week

**Comment by roemervandermeij** [comment]
@schoffelen, did you change anything else that you haven't pushed yet? Just so I don't repeat any changes (cfg.channel is no longer used in some (all?) cases)

**Comment by roemervandermeij** [comment]
Alright, see https://github.com/robertoostenveld/fieldtrip/pull/4

I've fixed a bunch of things. Channel selection works again, interactive browsing works with single and multiple datasets (data operations such as baselining are carried down the line again), datanaming is streamlined throughout the functions (I went with dataXXX again in case no name was present, as the inputXXX starting from 2 was a bit confusing), small bugs here and there are fixed. I've tested the most common operations for ER/TFR such as channel, freq, time selection, browsing back and forth, they look stable.

There's still something wrong with baselining ERF data. I suspect the cause lies in the cfg being changed after rollback_provenance, and ft_timelockbaseline being confused by it. It looks like baselining TFRs works well, but not tested exhaustively. I'll have a go at it tomorrow if nobody else has yet.

**Comment by schoffelen** [comment]
No, I haven't changed anything in addition @roemervandermeij . Branch should be clean

**Comment by roemervandermeij** [comment]
Alright, I'll look into to the baselining then today and any other issues I can find. Please hold of with the pull request https://github.com/robertoostenveld/fieldtrip/pull/4, I'll add more to it.

**Comment by roemervandermeij** [comment]
Okay, baselining failed down the line due to several reasons. 

The biggest one is not the most direct one, but is one that should be solved anyway. Baselining was done after averaging over repetitions. It is now done immediately prior to averaging. I'm not sure how this impacts chan_chan/chancmb data, which previously was 'handled' just prior to baselining. @schoffelen?

But the baseline failing also highlighted some other issues. 
What happened, when calling ...plotER with raw data, is (PRIOR to my baselining commit in https://github.com/robertoostenveld/fieldtrip/pull/4):
1) ft_checkdata replaces the raw data.trail cell array with a 3-way data.trial rpt_chan_time array
2) ft_selectdata with avgoverrpt = yes averages over the rpt dimensions, but keeps the field name as data.trial and sets dimord as chan_time
3) ft_timelockbaseline interprets the trial field as containing trials, sees channels as rpts and tries to baseline individual time points

If ft_selectdata would change the 'trial' field to 'avg', there would likely be no problem. Or, ft_timelockbaseline should use the dimord and not the field name as an indicator.

Also btw, ft_timelockbaseline does not use cfg.baselinetype at all, and does all baselining with ft_preproc_baseline. Is this intentional? In the documentation of ...plotER it says it allows 'absolute' and 'relative'. I also noticed that ft_timelockanalysis does not support baselining anymore? I'm surprised, as the default is keeptrials = no, and is also a key place to do the baselining. I'm pretty sure it used to be the case right? 
In the documentation of ft_timelockanalysis I now read:

> % Guidelines for use in an analysis pipeline:
% after FT_TIMELOCKANALYSIS you will have timelocked data - i.e., event-related
% fields (ERFs) or potentials (ERPs) - represented as the average and/or
% covariance over trials.
% This usually serves as input for one of the following functions:
%    * FT_TIMELOCKBASELINE      to perform baseline normalization

Baselining *after* averaging will not result in an ERF/P but something ghastly. This worries me quite a bit actually, cfg.baseline is not a forbidden option here.

**Comment by roemervandermeij** [comment]
Alright, I've fixed some more bugs and added them to the pull request. I've been testing for ~2 days and think I've gone through nearly all normal operations. Masking/highlighting in TFRs/ERs/topos, data selection, x/y/zlim, passing stuff through interactive mode keeping the expected cfgs, baselining, pre/post averaged input combined with baselining, TFR to PSD, raw to erf, multiple inputs in case of the ERs.

Thinks I haven't tested is the on-the-fly preproc and the channel type specific scaling.

Right now, the code looks very nicely synced between the functions. Any ideas on further modularization? I see bits and pieces, but it's hardly more than a few lines, and thus, won't give us much.

**Comment by robertoostenveld** [comment]
Thanks so much for all contributions.

Regarding the baseline correction in ft_timelockanalysis, that is handled around line 138

```
if ~isempty(cfg.preproc)
  % preprocess the data, i.e. apply filtering, baselinecorrection, etc.
  fprintf('applying preprocessing options\n');
  if ~isfield(cfg.preproc, 'feedback')
    cfg.preproc.feedback = cfg.feedback;
  end
  data = ft_preprocessing(cfg.preproc, data);
  [cfg.preproc, data] = rollback_provenance(cfg.preproc, data);
end
``` 

Regarding the baselining in ...plotER, I just made the (unused) cfg.baselinetype explicitly forbidden in ft_timelockbaseline.

**Comment by robertoostenveld** [comment]
Given the elaborate testing, I don't think we need an email to the discussion list. 

@schoffelen and @roemervandermeij: if you agree, I'll just merge it into the release.

**Comment by schoffelen** [comment]
👍

**Comment by roemervandermeij** [comment]
Re: ft_timelockanalysis
Ah, I hadn't realized this was now achieved with cfg.preproc via ft_checkconfig, sorry I got a little worried there. (I wouldn't necessarily agree with the current construction, but hey)

The only two things I had not tested are not commonly used I think (cfg.preproc en cfg.chanscale), and all the rest seemed very fine. So, good to go I'd say!

**Pull request merged**
