### PR TITLE
use gammaln instead of lgamma

### PR DESCRIPTION
**Pull request by gllmflndn**
See http://bugzilla.fieldtriptoolbox.org/show_bug.cgi?id=3312

### CODE REVIEW

**Comment by robertoostenveld** [comment]
that was fast! Do you want to include the other changes (e.g. ON/OFF) in here as well?

**Comment by gllmflndn** [comment]
See http://bugzilla.fieldtriptoolbox.org/show_bug.cgi?id=3310

**Comment by robertoostenveld** [comment]
thanks. Anything else that you want in here? If not, I'll merge.

**Comment by gllmflndn** [comment]
I think that should be it. Thanks!

**Comment by robertoostenveld** [comment]
just create another PR if there is more.

**Pull request merged**
