### PR TITLE
Bml neuroomega

### PR DESCRIPTION
**Pull request by abush84**
Support for NeuroOmega .mat files. Tested on Matlab 2015a

### CODE REVIEW

**Comment by schoffelen** [comment]
Looks like a clean contribution to me. I don't have my own data to test this with, so let's just pull this and see whether our battery of test functions handles this well.

As a side node (regarding startsWith and endsWith backward compatibility: we have a setup that allows for drop-in replacement for newer functionality in the folders e.g. fieldtrip/compat/matlablt2016b. I recently made a startsWith, to allow this function to be called from older matlab versions. We may consider adding some other functions as well.

**Comment by robertoostenveld** [comment]
The way of handling of channels with different sampling rates seems to be different than for other data formats (mainly EDF). That might be problematic, since the API (the way the code is to be called) would then be different for EDF files and for Omega files. 

I think that we should make a test script that shows how it works for both EDF and Omega. Could you please share an example (small) dataset for testing, or preferably two: one with homogenous sampling and one with variable sampling frequencies?

**Comment by abush84** [comment]
```
cfg=[];
cfg.dataset='LT1D9.975F0001.mat';
dat = ft_preprocessing(cfg);
```
Prints out a table with available channels, chantypes, Fs and then throughs an error. 

```
cfg=[];
cfg.dataset='LT1D9.975F0001.mat';
cfg.chantype={'macro','micro'};
dat1 = ft_preprocessing(cfg);
```
Loads the specified channel types. 

Here is a small example dataset.  All datasets have channels with different sampling frequencies.  

[LT1D9.975F0001.mat.zip](https://github.com/fieldtrip/fieldtrip/files/1422329/LT1D9.975F0001.mat.zip)

**Comment by robertoostenveld** [comment]
macro and micro are currently not valid channel types. See the implementation in ft_chantype.

**Pull request merged**
