### PR TITLE
Laggedcoherence

### PR DESCRIPTION
**Pull request by schoffelen**

### CODE REVIEW

**Comment by schoffelen** [comment]
@hadrianswall, can I merge?

**Comment by schoffelen** [comment]
@hadrianswall, can I merge?

**Comment by robertoostenveld** [comment]
I found that there are three test scripts related to this

```
failed_ft_connectivity_laggedcoherence.m
test_ft_connectivity_laggedcoherence.m
test_laggedcoherence.m
```

I tried all of them, and after some updates to the handling of cfg.channelcmb was able to get them all to work.

**Comment by robertoostenveld** [comment]
due to lack of input from @hadrianswall, I have taken this up. 

I reviewed the code: cleaned up the help and some code formatting issues. I did not change the actual code, except for the handling of channelcmb. I will first merge the contribution from @schoffelen and then add my own commit on top of that.

**Pull request merged**
