### PR TITLE
FIX - more robust source2volume conversions

### PR DESCRIPTION
**Pull request by schoffelen**

### CODE REVIEW

**Comment by schoffelen** [comment]
This PR aims to fix the regression error that causes test_ft_sourceinterpolate to fail.

Background:

a source structure that has 'pos_somethingelse' is currently not robustly converted into a volume data structure. That is: the numeric data field is not reshaped, and the <sth>dimord fields are still there.

even though it may need discussion as to whether a volume structure can contain >3D numeric data, the current suggested fix leads to a more stable output of ft_datatype_volume

**Comment by schoffelen** [comment]
BTW it seems to operate well enough on nested fields (avg.pow).

**Comment by schoffelen** [comment]
OK, this one is clearly not running robustly yet, stay tuned...

**Comment by schoffelen** [comment]
As discussed with @robertoostenveld I checked the codebase in more detail w.r.t. how the dim is used. As far as I can see, the dim - as used for a volume data structure - is used consistent enough for volume structure operations, e.g. with respect to ft_write_mri 

The statistics functions also internally rely on a cfg.dim field, which is somewhat uncoupled from the meaning of dim in a volume structure, in ft_statistics_<> and ft_<>statistics cfg.(orig)dim is used as a specifier for the (original) reshaped dimensions of the data vectors. 

I could have missed some more obscure applications, but I would be happy to merge for now, and see what happens.

**Comment by robertoostenveld** [comment]
I tested the code and started adding some stuff to `test_ft_checkdata`. There are still some issues with 

```
dim = [2 3 4];
transform = eye(4);
[X, Y, Z] = ndgrid(1:dim(1), 1:dim(2), 1:dim(3));
pos = ft_warp_apply(transform, [X(:) Y(:) Z(:)]);

data = [];
data.dim = dim;
data.pos = pos;
data.time = 1:5;
data.freq = 1:6;
data.coh = rand(prod(dim),1);
getdimord(data, 'coh')

data.coh = rand(prod(dim), length(data.time));
getdimord(data, 'coh')
tmp = ft_checkdata(data, 'datatype', 'volume')

data.coh = rand(prod(dim), length(data.time), length(data.freq));
getdimord(data, 'coh')
tmp = ft_checkdata(data, 'datatype', 'volume')

data.coh = rand(prod(dim), prod(dim));
getdimord(data, 'coh')
tmp = ft_checkdata(data, 'datatype', 'volume')

data.coh = rand(prod(dim), prod(dim), length(data.time));
getdimord(data, 'coh')
tmp = ft_checkdata(data, 'datatype', 'volume')

data.coh = rand(prod(dim), prod(dim), length(data.time), length(data.freq));
getdimord(data, 'coh')
tmp = ft_checkdata(data, 'datatype', 'volume')
```

I will work on it.

**Pull request merged**
