### PR TITLE
avoid web call + fix copyrights

### PR DESCRIPTION
**Pull request by agramfort**

### CODE REVIEW

**Comment by nno** [comment]
@agramfort and @eolivi looks great, thanks a lot. Much appreciated!

**Comment by mclerc** [comment]
Fine to remove it if it is annoying users, but copyright statement must be visible somewhere.

**Comment by agramfort** [comment]
@mclerc does the diff look good to you?

**Comment by mclerc** [comment]
Looks good to me !

**Comment by robertoostenveld** [comment]
thanks!

**Comment by papadop** [comment]
I'm sorry to arrive late in the conversation... 
I agree that the web call was too much all the more that it was there only where OpenMEEG was not used !!! 
On the other hand, it seems that even now, the copyright message is printed only whenever OpenMEEG is not properly installed. That seems awkward. In my view, it should on the contrary be printed only when it is installed (and even better at its first use in a session). There should also be a way for users to tell that they do not want to use OpenMEEG so that the error message no longer prints.

That being said, I have not seen the whole code just the patch, so I may not have understood the whole picture.

**Comment by robertoostenveld** [comment]
Hi Theodore,

I checked the license display, it was correct (most of the time), but I did make some improvements to make it more consistent. I also found out on my mac with 2016b that the binaries failed due to the library path not being set correctly. I made some improvements to that as well. I tested it on my mac, and will now test on linux to make sure that it works consistently. I don't have the ability to test on windows.

**Comment by robertoostenveld** [comment]
all tests (but one, which is still running) work fine on OS X and linux. Also on linux the license shows as expected. I'll merge the changes in the master. 

Interesting is to see the timing differences of the test jobs:

```
>> ft_test report fieldtripversion 33e9cbb
| matlabversion | fieldtripversion |           branch |    arch |  hostname |   user | passed | runtime |                    functionname |
-------------------------------------------------------------------------------------------------------------------------------------------
|         2016b |          33e9cbb | pull316-openmeeg |  maci64 |    mac011 | roboos |   true |     150 |                    test_bug1042 |
|         2016b |          33e9cbb | pull316-openmeeg |  maci64 |    mac011 | roboos |   true |       4 |                    test_bug1082 |
|         2016b |          33e9cbb | pull316-openmeeg |  maci64 |    mac011 | roboos |   true |      37 |                    test_bug1368 |
|         2016b |          33e9cbb | pull316-openmeeg |  maci64 |    mac011 | roboos |   true |       8 |                    test_bug2338 |
|         2016b |          33e9cbb | pull316-openmeeg |  maci64 |    mac011 | roboos |   true |     111 |                     test_bug686 |
|         2016b |          33e9cbb | pull316-openmeeg |  maci64 |    mac011 | roboos |   true |       7 |                      test_bug70 |
|         2016b |          33e9cbb | pull316-openmeeg |  maci64 |    mac011 | roboos |   true |       6 |         test_headmodel_openmeeg |
|         2016b |          33e9cbb | pull316-openmeeg |  maci64 |    mac011 | roboos |   true |      90 | test_headmodel_openmeeg_new_old |
|         2016b |          33e9cbb | pull316-openmeeg | glnxa64 | dccn-c008 | roboos |   true |     920 |                    test_bug1042 |
|         2016b |          33e9cbb | pull316-openmeeg | glnxa64 | dccn-c008 | roboos |   true |      15 |                    test_bug1082 |
|         2016b |          33e9cbb | pull316-openmeeg | glnxa64 | dccn-c008 | roboos |   true |     231 |                    test_bug1368 |
|         2016b |          33e9cbb | pull316-openmeeg | glnxa64 | dccn-c008 | roboos |   true |      95 |                    test_bug1756 |
|         2016b |          33e9cbb | pull316-openmeeg | glnxa64 | dccn-c008 | roboos |   true |      23 |                    test_bug2338 |
|         2016b |          33e9cbb | pull316-openmeeg | glnxa64 | dccn-c008 | roboos |   true |     615 |                     test_bug686 |
|         2016b |          33e9cbb | pull316-openmeeg | glnxa64 | dccn-c008 | roboos |   true |      18 |                      test_bug70 |
|         2016b |          33e9cbb | pull316-openmeeg | glnxa64 | dccn-c008 | roboos |   true |      30 |         test_headmodel_openmeeg |
```

On my MacBook it runs ~4x faster. I think that is to it being able to use 4 cores, whereas on the linux compute node in our cluster (dccn-c008) I know that it is restricted to a single core.

**Comment by nno** [comment]
> On my MacBook it runs ~4x faster. I think that is to it being able to use 4 cores, whereas on the linux compute node in our cluster (dccn-c008) I know that it is restricted to a single core.

Did you actually benchmark this specifically using ``maxNumCompThreads``? In my experience multi-cores computations generally do not lead to a near-linear speedup. Other factors may be I/O, RAM, caching, or even stuff like JIT implementation differences.

**Pull request merged**
