### PR TITLE
extend data2bids for more data types

### PR DESCRIPTION
**Pull request by robertoostenveld**
In the previous coding sprint, I mainly focused on EEG. Now I am specifically looking at all other data types.

Improvements in this PR include writing of electrode positions for eeg/ieeg and pure behavioral data (without biological data) in the `beh` directory

### CODE REVIEW

**Comment by robertoostenveld** [comment]
Since I still have to do https://github.com/fieldtrip/website/issues/134, I will keep this open for now.

**Comment by schoffelen** [comment]
> In the previous coding sprint, I mainly focused on EEG. Now I am specifically looking at all other data types.

And? Out of breath?

**Comment by robertoostenveld** [comment]
well, it is quite a long one. But nice to make progress, although some of it is probably not very relevant. I can now brag to @marcelzwiers that my data2bids does everything from behavioural to to electrophys to (f)MRI. The only thing to add (that I am aware of) is physio.

**Comment by schoffelen** [comment]
> well, it is quite a long one. But nice to make progress, although some of it is probably not very relevant. I can now brag to @marcelzwiers that my data2bids does everything from behavioural to to electrophys to (f)MRI. The only thing to add (that I am aware of) is physio.

And all that without a single yaml file.

**Comment by robertoostenveld** [comment]
there is now also an updated example, see http://www.fieldtriptoolbox.org/example/bids_eeg/

**Pull request merged**
