### PR TITLE
improve selection of spikes that fall within trials

### LINKED ISSUE #1554: Add .amplitude field to ft_spike_maketrials for segmentation into trials, and overwrite .samples field in new trial dimension
I'd like ft_spike_maketrials to also segment an additional amplitude field - when present - into trials.

Currently there are some try-catch statements that add a .waveform, .unit or .fourierspctrm field to the spike structure by ft_spike_maketrials. It would be easy to add an .amplitude field here.

Additionally, these trial-based fields currently overwrite existing 'raw' fields in the spike structure. However, .samples field stays in the original dimension, i.e. does not get segmented. 

The most consistent to me would be to create a trial-based .samples field, and overwrite the existing one. Then also segment into trials any other fields that have the same dimensions as the input raw structure. This would make the dimensions of the data consistent within a single data structure. 

Currently fields to be segmented are hard-coded. I am unsure / have no opinion about what would be a better. Hardcoded is easy (already done on my side). But I can make a PR of either.

### PR DESCRIPTION
**Pull request by robertoostenveld**
This closes #1554 and #1561

### CODE REVIEW

**Comment by robertoostenveld** [comment]
@stephenwhitmarsh can you review the suggested improvements in this pull request? I believe it addresses your problem

**Comment by stephenwhitmarsh** [comment]
@robertoostenveld - Thanks, it looks good, but what is the best way to actually test this since it's not merged yet?

I've tried: git checkout issue1554
to which it does switch branch, except that the code does not see changed as there compared to what I can see on github.
I'm missing something here... Any suggestion?

**Comment by stephenwhitmarsh** [comment]
I boiled it down to the question "how to checkout a remote pull request locally". I've added Robert as a remote, then tried every way to checkout the branch: to no avail:

Z:\fieldtrip>git remote -v
origin  https://github.com/stephenwhitmarsh/fieldtrip (fetch)
origin  https://github.com/stephenwhitmarsh/fieldtrip (push)
robert  https://github.com/robertoostenveld/fieldtrip (fetch)
robert  https://github.com/robertoostenveld/fieldtrip (push)
upstream        https://github.com/fieldtrip/fieldtrip (fetch)
upstream        https://github.com/fieldtrip/fieldtrip (push)

Z:\fieldtrip>git fetch robert pull/issue1554/head:issue1554
fatal: Couldn't find remote ref pull/issue1554/head

Z:\fieldtrip>git checkout -b issue1554 robert/issue1554
fatal: 'robert/issue1554' is not a commit and a branch 'issue1554' cannot be created from it

Z:\fieldtrip>git checkout -b issue1554 robertoostenveld/issue1554
fatal: 'robertoostenveld/issue1554' is not a commit and a branch 'issue1554' cannot be created from it

Z:\fieldtrip>git checkout -b robert robertoostenveld/issue1554
fatal: 'robertoostenveld/issue1554' is not a commit and a branch 'robert' cannot be created from it

Z:\fieldtrip>git checkout -b robert robertoostenveld/fieldtrip/issue1554
fatal: 'robertoostenveld/fieldtrip/issue1554' is not a commit and a branch 'robert' cannot be created from it

Z:\fieldtrip>git checkout -b robert fieldtrip/issue1554
fatal: 'fieldtrip/issue1554' is not a commit and a branch 'robert' cannot be created from it

Z:\fieldtrip>git checkout -b robert robertoostenveld:issue1554
fatal: 'robertoostenveld:issue1554' is not a commit and a branch 'robert' cannot be created from it

Z:\fieldtrip>git checkout -b robert robertoostenveld/fieldtrip:issue1554
fatal: 'robertoostenveld/fieldtrip:issue1554' is not a commit and a branch 'robert' cannot be created from it

**Comment by schoffelen** [comment]
Hi Stephen,
Would this work

git checkout -b issue1554  (this should switch to your branch issue1554, which does not have any changes)

followed by

git pull robert issue1554 (this pulls the branch issue1554 on robert's repo (which is the alias for the remote robertoostenveld/fieldtrip) into your branch issue1554

**Comment by stephenwhitmarsh** [comment]
> 
> 
> Hi Stephen,
> Would this work
> 
> git checkout -b issue1554 (this should switch to your branch issue1554, which does not have any changes)
> 
> followed by
> 
> git pull robert issue1554 (this pulls the branch issue1554 on robert's repo (which is the alias for the remote robertoostenveld/fieldtrip) into your branch issue1554

Great, thanks JM, that worked.

**Comment by stephenwhitmarsh** [comment]
@robertoostenveld I seem to have a little issue with getdimord:
```
SpikeTrials{ipart}.(markername)  = ft_spike_maketrials(cfgtemp, SpikeRaw{ipart});
the input is spike data with 14 channels
Undefined function 'getdimord' for input arguments of type 'struct'.

Error in ft_spike_maketrials (line 275)
      switch getdimord(spike, fn{i})
```

What is strange is that /private/getdimord.m is on the path (and I added it for good measure). /contrib/spike/private/getdimord.m even opens when I do 'edit getdimord'. Something seems off with the use of the private directory. 

When pulling the branch 1554, the getdimord was added BTW:
```
Z:\fieldtrip>git checkout -b issue1554
Switched to a new branch 'issue1554'

Z:\fieldtrip>git pull robert issue1554
remote: Enumerating objects: 50, done.
remote: Counting objects: 100% (50/50), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 50 (delta 42), reused 50 (delta 42), pack-reused 0
Unpacking objects: 100% (50/50), done.
From https://github.com/robertoostenveld/fieldtrip
 * branch                issue1554  -> FETCH_HEAD
 * [new branch]          issue1554  -> robert/issue1554
Merge made by the 'recursive' strategy.
 bin/synchronize-private.sh             |   2 +
 contrib/nutmegtrip/private/getdimord.m |  66 +--
 contrib/spike/ft_spike_maketrials.m    | 236 +++++-----
 contrib/spike/private/getdimord.m      | 756 +++++++++++++++++++++++++++++++++
 contrib/spike/private/getdimsiz.m      | 101 +++++
 fileio/private/ft_datatype_spike.m     |  97 +++--
 fileio/private/getdimord.m             |  66 +--
 forward/private/getdimord.m            |  66 +--
 private/getdimord.m                    |  66 +--
 test/private/getdimord.m               |  66 +--
 test/test_issue1554.m                  |  95 +++++
 utilities/ft_datatype_spike.m          |  97 +++--
 utilities/private/getdimord.m          |  66 +--
 13 files changed, 1416 insertions(+), 364 deletions(-)
 create mode 100644 contrib/spike/private/getdimord.m
 create mode 100644 contrib/spike/private/getdimsiz.m
 create mode 100644 test/test_issue1554.m
```

**Comment by robertoostenveld** [comment]
getdimord is in fieldtrip/private, but was not in fieldtrip/contrib/spike/private (where ft_spike_maketrials) would look for it). I thought I added it there, but apparently not. For testing purposes you can just copy it there.

**Comment by stephenwhitmarsh** [comment]
> 
> 
> getdimord is in fieldtrip/private, but was not in fieldtrip/contrib/spike/private (where ft_spike_maketrials) would look for it). I thought I added it there, but apparently not. For testing purposes you can just copy it there.
> 
> Edit: oh nevermind, you already checked that in detail. Try a `clear all` to see whether MATLAB refreshes its path.

Okay, thanks, clearing all now. Yeah something seems stuck (have you tried turning it off and back on again? ;-)). It will take a little while to get everything back in memory and test.

**Comment by stephenwhitmarsh** [comment]
Hi @robertoostenveld 
The new implementation doesn't give expected results on my study data; e.g.:

```
SpikeTrials{ipart}.(markername).sample

ans =

  1×14 cell array

    {1×16971 uint64}    {1×243455 uint64}    {1×528175 uint64}    {1×10958 uint64}    {1×541904 uint64}    {1×751867 uint64}    {1×819849 uint64}    {1×126214 uint64}    {1×55414 uint64}    {1×58992 uint64}    {1×1042807 uint64}    {1×541904 uint64}    {1×751867 uint64}    {1×819849 uint64}

K>> SpikeTrials{ipart}.(markername).timestamp

ans =

  1×14 cell array

    {1×0 uint64}    {1×9 uint64}    {1×21 uint64}    {1×0 uint64}    {1×20 uint64}    {1×11 uint64}    {1×48 uint64}    {1×0 uint64}    {1×0 uint64}    {1×0 uint64}    {1×0 uint64}    {1×20 uint64}    {1×11 uint64}    {1×48 uint64}
```

As you can see, the .sample field was not updated, while the timestamp data shows problems parsing the data into trials (see empty cells), which was also reflected in the .time and .trial fields.

I tried to simply revert to my master branch, but MATLAB won't have it. I'll restart the analyses, and take a look at the test script as well, and see how the function is different with respect to trial selection. For now, I would say the function shouldn't be merged.

By the way, when the dimord function send a warning that it was not able to determine the dimensions of the other fields, it did so with a print of the whole datastructure. Which, when multiplied with the number of units, became quite a long list. I don't remember the dimord function outputting the whole datastructure, maybe that changed as well?

**Comment by robertoostenveld** [comment]
the `dimord` function has always outputted the whole structure but was not used here before. Doing it multiplied with the number of units is of course not needed. Better would be to get the list of potentially interesting fields and their dimord only once outside the loop over units.

**Comment by stephenwhitmarsh** [comment]
Ah, something is clearly off in the loop; the outputting of the whole datastructure actually showed how the .time and .trial fields progressively filled in with an incremental list (1:14):
```
                time: {{1×1 cell}  {1×2 cell}  {1×3 cell}  {1×4 cell}  {1×5 cell}  {1×6 cell}  {1×7 cell}  {1×8 cell}  {1×9 cell}  {1×10 cell}  {1×11 cell}  {1×12 cell}  {1×13 cell}  {1×14 cell}}
```

**Comment by stephenwhitmarsh** [comment]
Ah, okay, I think I spotted it.

See the creation of ```waveSel``` on line 267. It should be used instead of ```sel``` in the next block of code, i.e. line 278, 281, 284.

**Comment by stephenwhitmarsh** [comment]
Sorry, that does not suffice. There is more at hand.

**Comment by stephenwhitmarsh** [comment]
I fixed the fix here:
https://github.com/robertoostenveld/fieldtrip/pull/10

I can also do a PR directly to FT's main, but this seemed more appropriate. Let me know!

Cheers and thanks,
Stephen

**Review by stephenwhitmarsh — APPROVED** [review]
All works well now, please merge.

**Pull request merged**
