### PR TITLE
something is wrong with ft_appendsens, but it is unclear what

### PR DESCRIPTION
**Pull request by StolkArjen**
…montage

### CODE REVIEW

**Comment by robertoostenveld** [comment]
please describe what the desired functionality is.

Are channels appended and are overlapping channels in multiple input dealt with?

Are electrodes appended and are overlapping electrodes in multiple input dealt with?

**Comment by StolkArjen** [comment]
Let me first describe example behavior of two different rereferencing schemes, with the open question regarding ft_appendsens' behavior culminating @Observation #3:

Situation #1: Rereferencing with reref = 'yes' (new implementation):

cfg               = [];
cfg.channel       = ft_channelselection({'LPG*', 'LTG*'}, data.label);
cfg.reref      	  = 'yes';
cfg.refchannel    = 'all';
cfg.updatesens    = 'yes';
reref_grids = ft_preprocessing(cfg, data);

reref_grids.elec
         cfg: [1x1 struct]
     chanpos: [64x3 double]
    coordsys: 'tal'
     elecpos: [152x3 double]
       label: {64x1 cell}
        unit: 'mm'
         tra: [64x152 double]


Situation #2: Rereferencing with cfg.montage:

cfg                    = [];
cfg.channel            = ft_channelselection('RAM*', data.label);
cfg.montage.labelold   = cfg.channel;
  cfg.montage.labelnew   = strcat(cfg.channel(1:end-1),'-',cfg.channel(2:end));
  cfg.montage.tra        = ...
  [1    -1     0     0     0     0     0     0
    0     1    -1     0     0     0     0     0
    0     0     1    -1     0     0     0     0
    0     0     0     1    -1     0     0     0
    0     0     0     0     1    -1     0     0
    0     0     0     0     0     1    -1     0
    0     0     0     0     0     0     1    -1];
  cfg.updatesens         = 'yes';
reref_depths = ft_preprocessing(cfg, data);

reref_depths.elec
           cfg: [1x1 struct]
       chanpos: [7x3 double]
      coordsys: 'tal'
       elecpos: [152x3 double]
         label: {7x1 cell}
          unit: 'mm'
           tra: [7x152 double]
    chanposold: [152x3 double]
      labelold: {152x1 cell}

>Observation #1: the second situation additionally produces a chanposold and labelold field. At appending the two schemes using ft_appendsens, one cannot ensures that the chanposold and labelold fields also apply to the first situation. Hence, the new ft_appendsens only appends these fields (i.e. copies m over from the first input) if they are identical across all inputs, e.g. (where labelold is a cell array with each input's labelold field)

if haslabelold && all(strcmp(labelold{1}, labelold))
  sens.labelold = labelold{1};
end

>Observation #2: the chanpos and label fields differ, obviously. Given that the crucial fields that need appending, ft_appendsens concatanes those (unchanged behavior).

>(!) Observation #3: this is more tricky. Both inputs have an elecpos field, and the question that arises is: do we want to simply concatenate them and remove duplicates afterwards, orrrr..  check whether they are identical across inputs and then copy m over from the first input, such as described at Observation #1? Only in this last scenario, we are able to merge the tra fields as well. If we would simply concatenate and remove duplicates, we cannot assure that the relationship between elecpos and chanpos still holds. Whereas if we check whether all inputs are actually originating from the recording, then we are presumably safe to copy over an elecpos field and merge the tra fields. Only drawback I can think of, is that using ft_appendsens on two inputs coming from different recordings will produce a chanpos and label, but no elecpos and no tra field. If the elecpos is still desired, we could have ft_appendsens still concatenate it but not merge the tra field (which is done only when the inputs come from the same recording).

**Comment by StolkArjen** [comment]
Found and repaired a hypothetical situation producing output inconsistent with the neural data (i.e. 6 elec.chanpos instead of the desired 3). The repair involved checking for and removing duplicate channel names, which keeps elec consistent with the data it's a description of:

% data_eeg
data_eeg.label = {'eeg 1';'eeg 2';'eeg 3'};
data_eeg.trial{1,1} = randn(3,10);
data_eeg.time{1,1} = 1:10;
data_eeg.elec.label = data_eeg.label;
data_eeg.elec.elecpos = [1 1 1; 2 2 2; 3 3 3];
data_eeg.elec.chanpos = [1 1 1; 2 2 2; 3 3 3];
data_eeg.elec.tra = eye(3);

% data_eeg2 (a different EEG recording: same labels but different elecpos)
data_eeg2 = data_eeg;
data_eeg2.elec.elecpos = [1 1 1; 2 2 2; 3 3 3]+1; % note the +1
data_eeg2.elec.chanpos = [1 1 1; 2 2 2; 3 3 3]+1; % note the +1

cfg = [];
cfg.appendsens = 'yes';
append1 = ft_appenddata(cfg, data_eeg, data_meg);

append0 = 

    label: {3x1 cell}
     elec: [1x1 struct]
    trial: {[3x10 double]  [3x10 double]}
     time: {[1 2 3 4 5 6 7 8 9 10]  [1 2 3 4 5 6 7 8 9 10]}
      cfg: [1x1 struct]

append0.elec

     chanpos: [3x1 double]
    chantype: {3x1 cell}
    chanunit: {3x1 cell}
       label: {3x1 cell}
        unit: 'dm'
         cfg: [1x1 struct]

Note that the chanpos of data_eeg2, in contrast to the label, is not identical that of data_eeg. We could make ft_appendsens decide to remove chanpos all together. For now, I made it to throw a warning:

Warning: duplicate channel labels found and removed, assuming that the chanpos fields match 
> In ft_appendsens (line 154)

**Comment by StolkArjen** [comment]
Main doc change:

% A call to FT_APPENDSENS results in the label, chanpos, and when applicable, 
% the chanori fields to be concatenated. Any duplicates will be removed. 
% Moreover, the elecpos, labelold, and chanposold fields are copied over
% from the first input under the condition that these fields are identical 
% across the inputs. If applicable, the tra matrices are also merged.

**Comment by robertoostenveld** [comment]
fieldtrip itself is not using chanposold and labelold. whenever it is unclear what to do with it, they should be removed. 

please describe what the desired functionality is:

Are channels appended and are overlapping channels in multiple input dealt with?
a) yes
b) no
c) I prefer to give fuzzy answers

Are electrodes appended and are overlapping electrodes in multiple input dealt with?
a) yes
b) no
c) I prefer to give fuzzy answers

**Comment by StolkArjen** [comment]
TBC

**Pull request closed without merging**
