### PR TITLE
Brainnetome atlas

### PR DESCRIPTION
**Pull request by juangpc**
Hi, 

I've managed  to add compatibility between Brainnetome atlas and fieldtrip. IMHO of special interest for functional connectivity works.

- changes in ft_read_atlas. These are totally compatible with all previous atlases. I've only added an extra comparison. When dealing with a .nii atlas and checking for a label file. Only if the file starts with "Brainnetome Atlas" in its first line, the specific case will be executed, in any other case, the function ft_read_atlas will behave exactly as it used to.

- added BNA_MPM_thr25_1.25mm.nii atlas and BNA_MPM_thr25_1.25mm.txt label file. 
One main concern is that BNA_MPM_thr25_1.25mm.nii is 14mB. However its zipped version is only 168kB. All these files where downloaded from http://www.brainnetome.org.

### CODE REVIEW

**Comment by robertoostenveld** [comment]
Thanks. Could you please add a paragraph documenting the Brainnetome atlas on http://www.fieldtriptoolbox.org/template/atlas? Look there for some examples. The motivation for this documentation is (shortly) explained in the intro on http://www.fieldtriptoolbox.org/template.

**Comment by juangpc** [comment]
Shure! You're welcome.

I've added some description just like previous atlases. Although I've added
the code as if the atlas was already located in the /template/atlas/ folder
inside its own sub-folder.

***Important.***
Note that I only want to help. If there is some other place where the files
should be better held. I have absolutely no problem. *But then, the example
code must be edited accordingly*.

See the update --> http://www.fieldtriptoolbox.org/template/atlas

I'm unable to present the image capture with shadow.

Hope it does help.

Best,



Juan

**Comment by robertoostenveld** [comment]
I have made my own branch and pulled your suggestion for review
mac011> git checkout -b pull331-brainnetome
mac011> git pull https://github.com/juangpc/fieldtrip.git brainnetome_atlas

after 

```
>> atlas = ft_read_atlas('BNA_MPM_thr25_1.25mm.nii');
>> cfg = [];
>> cfg.atlas = atlas;
>> cfg.funparameter = 'tissue'
>> ft_sourceplot(cfg, atlas)
```

and looking in the txt file, I see that

```
SFG, Right Superior Frontal Gyrus  A8m, medial area 8
MFG, Right Middle Frontal Gyrus A9/46v, ventral area 9/46
OrG, Right Orbital GyrusA11m, medial area 11
```

Sometimes there are two spaces, sometimes one, sometimes none. I think that is a bug. Can you fix that?

**Comment by juangpc** [comment]
:S

Let me have a look.


Juan

**Comment by robertoostenveld** [comment]
I also tried this

```
atlas.pow = randn(size(atlas.tissue)); % pretend it is a source estimate
cfg = []
cfg.parameter = 'pow'
cfg.parcellation = 'tissue'
parcellated = ft_sourceparcellate(cfg, atlas)
```

and realized that deep inside the private "fixsegmentation" function something was rather inefficient. I have made a fix for that (on my pull331-brainnetome branch). That will also be merged once all issues are resolved.

**Comment by juangpc** [comment]
Yes. I extracted the labels from an excel file where there probably are some extra spaces here and there. 
Problem solved. file pushed.

Great about the parcellation (I didn't know about sourceparcellate). I've a lot to learn still. Ufff.

**Comment by robertoostenveld** [comment]
there are still inconsistencies in spaces. Please search for "  " (two spaces) and for "LobuleA" (where there should be a space in between. Capitalization is also not consistent (sometimes I see gyrus, sometimes Gyrus), there is a " )" space before a closing bracket, and some but not all opening brackets have a space in front of them.

**Comment by juangpc** [comment]
corrected:

- two double spaces,
- the LobuleA typos,
- the " )"
- a few missing spaces before opening brackets.
- one Gryrus with uppercase that should've been a lowercase.

-> I've left some Gyrus with capitla G and others with lowercase, just as
the authors do.

These typos, and the difference between when to use G and g for gyrus,
derive all from the excel file where the authors define each area. It is
downloadable from here: http://atlas.brainnetome.org/download.html. It's
attached, in case you want to have have a look at it.






Juan

On Fri, Feb 17, 2017 at 6:50 PM, Robert Oostenveld <notifications@github.com

**Comment by robertoostenveld** [comment]
it looks good now, I'll merge it into the release.

**Comment by robertoostenveld** [comment]
oops, another commit coming in ;-) 
let me know when you are all done.

**Comment by juangpc** [comment]
done.


Juan

On Fri, Feb 17, 2017 at 7:37 PM, Robert Oostenveld <notifications@github.com

**Comment by robertoostenveld** [comment]
it is now in the release version, thanks for the contribution!

**Comment by juangpc** [comment]
I should say, thanks to you. learning+ while doing this.


Juan

On Fri, Feb 17, 2017 at 7:42 PM, Robert Oostenveld <notifications@github.com

**Pull request merged**
