### PR TITLE
FIX+OCTAVE: simplify ft_{pre,post}amble for Octave

### PR DESCRIPTION
**Pull request by nno**
This PR tries to address the issue that surfaced on travis (https://travis-ci.org/nno/fieldtrip/jobs/196967097) where the current implementation of ft_preamble does not work properly in Octave when ft_preamble gets called recursively. The present attempt does so by a temporary ``cd`` into the private directory, and executes commands from there. As far as I can tell Octave is happy (or at least, happier).

Note that this PR also changes behaviour of ft_{pre,post}amble: typically supported commands are ``debug``,``init``,``loadvar``,``provenance``,``randomseed`` and ``trackconfig``. In this PR an error is now thrown if the input argument``cmd`` is referring to an unsupported command (rather than quitting silently). Thus, previous versions of FieldTrip are fine with 
```
    ft_defaults foo
```
whereas with the current PR such a command raises an error.

@robertoostenveld if you agree it is good to raise an error if an unsupported value for the input argument ``cmd`` is used, it is probably a good idea to run the full test suite on the changed code before merging. I tried to find / grep all occurences of ft_{pre,post}amble

### CODE REVIEW

**Comment by robertoostenveld** [comment]
I ran a batch and got 
```
roboos@mentat001> grep FAILED *.txt
test_bug3192.txt:=== test_bug3192 FAILED in 21 seconds
test_ft_spikedensity.txt:=== test_ft_spikedensity FAILED in 0 seconds
test_ft_spike_isi.txt:=== test_ft_spike_isi FAILED in 1 seconds
test_ft_spike_jpsth.txt:=== test_ft_spike_jpsth FAILED in 1 seconds
test_ft_spike_plot_isireturn.txt:=== test_ft_spike_plot_isireturn FAILED in 1 seconds
test_ft_spike_plot_raster.txt:=== test_ft_spike_plot_raster FAILED in 6 seconds
test_ft_spike_psth.txt:=== test_ft_spike_psth FAILED in 1 seconds
test_ft_spike_rate.txt:=== test_ft_spike_rate FAILED in 1 seconds
test_ft_spiketriggeredspectrum_stat.txt:=== test_ft_spiketriggeredspectrum_stat FAILED in 9 seconds
test_ft_spiketriggeredspectrum.txt:=== test_ft_spiketriggeredspectrum FAILED in 1 seconds
test_ft_spike_xcorr.txt:=== test_ft_spike_xcorr FAILED in 1 seconds
test_tutorial_spike_Neurosim.txt:=== test_tutorial_spike_Neurosim FAILED in 0 seconds
```

all seem to be related to ft_preamble_callinfo, and all are in contrib/spike. I suspect this is an outdated preamble that was not removed/updated there.

**Comment by nno** [comment]
Thanks @robertoostenveld, I will look into it.

**Comment by robertoostenveld** [comment]
I am already on it, so please hold back. 
Once this is fixed, I'll also run it with some other matlab versions.

**Comment by nno** [comment]
All right, thanks.

**Comment by robertoostenveld** [comment]
I tested (most of) the test batch on 2016b, 2015b, 2014b and 2011b. Not all ran through cleanly, especially not on 2011b, but the problems were not related to the pre/postamble. 

Thanks for the contribution.

**Comment by nno** [comment]
You're welcome, and thanks for making the adjustments in #363.

**Pull request merged**
