### PR TITLE
enh: added slice feature to ft_plot_cloud

### PR DESCRIPTION
**Pull request by smg211**
ft_plot_cloud can now plot 2D slices through point clouds, with an outline of an intersecting mesh (similar to ft_plot_slice).  Additionally, outlines of the intersecting mesh at a particular slice can also be plotted on the meshes themselves (with the point clouds, in 3D) to aide in interpreting the 2D slice output.  See attached for figures.
slice 3d
slice 2d

### CODE REVIEW

**Comment by robertoostenveld** [comment]
please add the new functionality to the plotting/test/test_ft_plot_cloud. This can be with a simple spherical mesh, i.e. des not need real data.

**Comment by smg211** [comment]
Hi Robert,

I added a few meshes and some code for testing the slice functionality to plotting/test/test_ft_plot_cloud.m  I will make sure to create/add to a test script for this sort of thing in the future.

Thanks,
Sandon

**Comment by robertoostenveld** [comment]
I have merged, but will still do a quick review it in the master branch on my local computer.

**Comment by smg211** [comment]
Sounds good, thanks Robert!

**Pull request merged**
