### PR TITLE
blackrock NEV

### PR DESCRIPTION
**Pull request by abush84**
Completed ft_read_header for blackrock_nev

### CODE REVIEW

**Comment by schoffelen** [comment]
Sorry Alan, but after having pulled your PR implementing the neuroOmega reading, this PR is conflicted with the master branch. I looked at it briefly, but am reluctant to fix it, afraid to break the intended functionality. Would you mind to fix it on your end in a commit to this PR?
Thanks in advance

**Comment by robertoostenveld** [comment]
I resolved the conflicts, the PR is now clean and can be merged.

**Comment by robertoostenveld** [comment]
note that I have not tested the new functionality, as I don't have example files.

**Comment by agramfort** [comment]
FYI we have started to collect files in different formats here:

https://web.gin.g-node.org/NeuralEnsemble/ephy_testing_data

you have files in blackrock format there.

if you have more files let's centralized them here?

HTH

**Comment by robertoostenveld** [comment]
Thanks, that is a useful collection. Many test files that I have (on our own compute server) were sent/shared by researchers without explicit agreement of re-distribution or sharing. I will have to look at whether they are anonymous before I can share them and I will have to rename them.

**Comment by schoffelen** [comment]
The data that I have put on /home/common were obtained from the blackrock people themselves, so that should be fine

**Comment by agramfort** [comment]
it would great to share as much as possible.thanks

**Pull request merged**
