### PR TITLE
bugfix2304 - fixed artifact browsing and made robust to artifacts not…

### PR DESCRIPTION
**Pull request by roemervandermeij**
… overlapping with segmented data and those that are split over segments/trials

### CODE REVIEW

**Comment by roemervandermeij** [comment]
I was reorganizing my github branch, causing in the end to remove the pull request, hence the reinitiating (not meant as a push ;)).

**Comment by roemervandermeij** [comment]
I added another commit to this branch due to potential conflicts with the first commit (not functionally, but it's in the same spot). The content of 2nd commit is related to a feature I added in a previous pull request, and since the current pull request hadn't been accepted yet, it could just as well piggyback on it.

**Comment by robertoostenveld** [comment]
ik hoop dat het allemaal goed gaat... en anders zien we het wel.

**Comment by roemervandermeij** [comment]
Lijkt allemaal goed te zijn gegaan! Thanks.

**Pull request merged**
