### PR TITLE
fixing bug1152

### PR DESCRIPTION
**Pull request by ualsbombe**

### CODE REVIEW

**Comment by robertoostenveld** [comment]
Looks good to me.
 
@ualsbombe have you tested this with different datasets (not only planar and mags, but also with EEG?)

**Comment by schoffelen** [comment]
Ah, I think I clicked the wrong button. I approve of the change, but I would like to see some additional changes in the documentation and the cfg handling.

**Comment by ualsbombe** [comment]
The change is no good - cfg.channel has no function - no matter what you put in - all channels are shown - including trigger channels. Anyway to revert it?

**Comment by schoffelen** [comment]
Hi @ualsbombe Lau, What's the status of this? I don't know in whose court the ball is, could you have quick look at it to get it resolved?

**Comment by ualsbombe** [comment]
Hi Jan-Mathijs

By mistake, I created two pull requests for this. The other one (with the correct solution) was pulled some days ago (https://github.com/fieldtrip/fieldtrip/pull/1281).

I'll delete this one accordingly.

All the best

Lau

**Pull request closed without merging**
