### PR TITLE
RICOH and YOKOGAWA MEG Reader toolboxes and thier related functions

### PR DESCRIPTION
**Pull request by KiwamuK**
# Suggestion 
We would like FieldTrip to support Ricoh MEG data by providing its reader toolbox and the related functions. We also would like to update the Yokogawa toolbox form ver. 1.4 to 1.5 this time. 

# Pull requested Files
 
・RICOH MEG READER toolbox　(\fieldtrip\external\ricoh_meg_reader) [16 files]
 This toolbox is composed of 13 reader functions (P-codes) for Ricoh data, contents.m, 
 Toolbox specification document (pdf), and EULA (pdf). 
 RICOH MEG system is similar to YOKOGAWA MEG system, and thus the ricoh_meg_reader toolbox 
 is almost same as the yokogawa_meg_reader toolbox (ver 1.4 [current version]) 
 although the filenames have been changed from *Ykgw*  ---> *R*. 
 The file “contents.m” describes reader functions briefly. 

・YOKOGAWA MEG READER toolbox ver. 1.5  (\fieldtrip\external\yokogawa_meg_reader) [16 files]
 We updated the yokogawa_meg_reader from ver. 1.4 to 1.5. 
 The reader ver. 1.5 newly supports EEG data. 
 This toolbox is composed of 13 reader functions (P-codes) for Yokogawa data, contents.m, 
 Toolbox specification document (pdf), and EULA (pdf). 
 The file “contents.m” describes reader functions briefly. 

・New files for Ricoh data [7 files]
\fileio\private\
	hasricoh.m
	isricohmegfile.m
	read_ricoh_data.m
	read_ricoh_event.m (will call getRHdrAnnotation.p)
	read_ricoh_header.m
	ricoh2grad.m
\test\
	test_ricoh.m
		--- Test function for Ricoh data

*NOTE(1): There are three extensions for Ricoh system, *.con, *.ave, and *.mrk. 
 Yokogawa system also has the three extensions in addition to *.raw, .*mri, etc. 
 Therefore, the filetypes, ricoh_con, ricoh_ave, and ricoh_mrk are newly defined 
 to distinguish from yokogawa_con, yokogawa_ave, and yokogawa_mrk. 
 The file type, .con, .ave, and .mrk of Ricoh and Yokogawa are distinguished 
 by the function, isricohmegfile.  

*NOTE(2): An example data, an “exported *.con file” for "test_ricoh.m", can be downloaded here: 
 https://www.dropbox.com/s/6ysmuvstf1u5tyr/RICOH160-1_MEGEEG_DATA_AEF.zip?dl=0 

・A modified file for Yokogawa data [1 file]
\fileio\private\
	hasyokogawa.m 
		--- The wording of comment has been changed (L45-46). 
		--- L80-89 has been commented out and L93-95 has been added to secure 
			that “All reference channels are excluded”

・ft_*.m files with suggested changes [8 files]
\fileio\
	ft_chanunit.m
		--- Channel units for 'eeg', 'refmag', 'trigger' have been defined. 
	ft_filetype.m
		--- Ricoh file types have been defined in a way parallel to Yokogawa’s ones [L329-363]. 
			The function, “isricohmegfile.m”, is used. 
	ft_read_data.m
		--- The case of 'ricoh_ave' and 'ricoh_con' has been added [L1379-1383]. 
	ft_read_event.m
		--- The case of 'ricoh_ave' and 'ricoh_con' has been added [L1994-2007]. 
	ft_read_header.m
		--- The case of 'ricoh_ave', 'ricoh_con', and ‘ricoh_mrk’ has been added [L2359-2364].
	ft_read_headshape.m
		--- The case of 'ricoh_ave', 'ricoh_con', and ‘ricoh_mrk’ has been added [L500-563].
			The case of 'yokogawa_ave', 'yokogawa_con', and ‘yokogawa_mrk’ has been rewritten 
			in the same way for Ricoh’s case [L565-660]. 
			Part of the previous code for Yokogawa data has been commented out [L699-734]. 
			The case of 'yokogawa_raw' has been separated off from the case of 
			'yokogawa_ave', 'yokogawa_con', and ‘yokogawa_mrk’ [L662-684]. 
	ft_read_sens.m
		--- The 'ricoh_ave' and 'ricoh_con' have been added in a way parallel to Yokogawa’s ones. 
\fileio\private\
	ft_hastoolbox.m 
		--- RICOH_MEG_READER has been added at L243-244. Version of YOKOGAWA_MEG_READER 
			has been changed from 1.4 to 1.5 [L242]. 

For additional information on Ricoh data, see "Getting started with Ricoh data"
http://www.fieldtriptoolbox.org/getting_started/ricoh

<List of files>
new file:   external/ricoh_meg_reader/Contents.m<br>
new file:   external/ricoh_meg_reader/EULAforRICOHMEGReaderToolbox.pdf<br>
new file:   external/ricoh_meg_reader/RICOHMEGReaderToolbox_1.0_specifications.pdf<br>
new file:   external/ricoh_meg_reader/getRData.p<br>
new file:   external/ricoh_meg_reader/getRHdrAcqCond.p<br>
new file:   external/ricoh_meg_reader/getRHdrAnnotation.p<br>
new file:   external/ricoh_meg_reader/getRHdrChannel.p<br>
new file:   external/ricoh_meg_reader/getRHdrCoregist.p<br>
new file:   external/ricoh_meg_reader/getRHdrDigitize.p<br>
new file:   external/ricoh_meg_reader/getRHdrEvent.p<br>
new file:   external/ricoh_meg_reader/getRHdrSource.p<br>
new file:   external/ricoh_meg_reader/getRHdrSubject.p<br>
new file:   external/ricoh_meg_reader/getRHdrSystem.p<br>
new file:   external/ricoh_meg_reader/getRMriHdr.p<br>
new file:   external/ricoh_meg_reader/getRVersion.p<br>
new file:   external/ricoh_meg_reader/private/GetSqf.p<br>
modified:   external/yokogawa_meg_reader/Contents.m<br>
new file:   external/yokogawa_meg_reader/EULAforYOKOGAWAMEGReaderToolbox.pdf<br>
deleted:    external/yokogawa_meg_reader/GetSqf.p<br>
deleted:    external/yokogawa_meg_reader/YokogawaMEGReaderToolbox_1.4_specifications.pdf<br>
new file:   external/yokogawa_meg_reader/YokogawaMEGReaderToolbox_1.5_specifications.pdf<br>
deleted:    external/yokogawa_meg_reader/getYkgwData.m<br>
modified:   external/yokogawa_meg_reader/getYkgwData.p<br>
deleted:    external/yokogawa_meg_reader/getYkgwHdrAcqCond.m<br>
modified:   external/yokogawa_meg_reader/getYkgwHdrAcqCond.p<br>
deleted:    external/yokogawa_meg_reader/getYkgwHdrBookmark.m<br>
modified:   external/yokogawa_meg_reader/getYkgwHdrBookmark.p<br>
deleted:    external/yokogawa_meg_reader/getYkgwHdrChannel.m<br>
modified:   external/yokogawa_meg_reader/getYkgwHdrChannel.p<br>
deleted:    external/yokogawa_meg_reader/getYkgwHdrCoregist.m<br>
modified:   external/yokogawa_meg_reader/getYkgwHdrCoregist.p<br>
deleted:    external/yokogawa_meg_reader/getYkgwHdrDigitize.m<br>
modified:   external/yokogawa_meg_reader/getYkgwHdrDigitize.p<br>
deleted:    external/yokogawa_meg_reader/getYkgwHdrEvent.m<br>
modified:   external/yokogawa_meg_reader/getYkgwHdrEvent.p<br>
deleted:    external/yokogawa_meg_reader/getYkgwHdrSource.m<br>
modified:   external/yokogawa_meg_reader/getYkgwHdrSource.p<br>
deleted:    external/yokogawa_meg_reader/getYkgwHdrSubject.m<br>
modified:   external/yokogawa_meg_reader/getYkgwHdrSubject.p<br>
deleted:    external/yokogawa_meg_reader/getYkgwHdrSystem.m<br>
modified:   external/yokogawa_meg_reader/getYkgwHdrSystem.p<br>
deleted:    external/yokogawa_meg_reader/getYkgwMriHdr.m<br>
modified:   external/yokogawa_meg_reader/getYkgwMriHdr.p<br>
deleted:    external/yokogawa_meg_reader/getYkgwVersion.m<br>
modified:   external/yokogawa_meg_reader/getYkgwVersion.p<br>
new file:   external/yokogawa_meg_reader/private/GetSqf.p<br>
modified:   fileio/ft_chanunit.m<br>
modified:   fileio/ft_filetype.m<br>
modified:   fileio/ft_read_data.m<br>
modified:   fileio/ft_read_event.m<br>
modified:   fileio/ft_read_header.m<br>
modified:   fileio/ft_read_headshape.m<br>
modified:   fileio/ft_read_sens.m<br>
modified:   fileio/private/ft_hastoolbox.m<br>
new file:   fileio/private/hasricoh.m<br>
modified:   fileio/private/hasyokogawa.m<br>
new file:   fileio/private/isricohmegfile.m<br>
new file:   fileio/private/read_ricoh_data.m<br>
new file:   fileio/private/read_ricoh_event.m<br>
new file:   fileio/private/read_ricoh_header.m<br>
new file:   fileio/private/ricoh2grad.m<br>
modified:   fileio/private/yokogawa2grad_new.m<br>
new file:   test/test_ricoh.m

### CODE REVIEW

**Comment by schoffelen** [comment]
Ah, I didn't read until the end, but there seem to be some conflicts with some of the fileio functions. Please fix these and commit a clean version to be merged.

**Comment by schoffelen** [comment]
Thanks for resolving the conflicts! Could you also have a look at the test-function, as per my previous comment?

**Comment by robertoostenveld** [comment]
I have downloaded the test file and copied it to our storage system as /home/common/matlab/fieldtrip/data/test/original/meg/ricoh160/rightearAEF_export.con

I am now running the test_ricoh script (on macOS and MATLAB 2017b) and will make the required changes to the test script regarding test file location.

**Comment by robertoostenveld** [comment]
Thanks, I have merged the proposed changes into the release version (aka the master branch). The whole batch of test scripts (i.e. all files starting with test_ in the fieldtrip/test directory) will run this evening (CET). I will keep an eye out for unexpected regression errors.

**Comment by KiwamuK** [comment]
Jan and Robert, thank you for encouraging me, correcting the test function, and merging the codes!

**Pull request merged**
