### PR TITLE
Update ft_headmovement.m

### PR DESCRIPTION
**Pull request by Michelmann**
before only positions that occurred at least 100 times in the data were considered. This way an empty dat was passed to kmeans. 
Now every position is considered.

### CODE REVIEW

**Comment by robertoostenveld** [comment]
This is a quite old and little used function. Could you make a test script (see for examples fieldtrip/test) that demonstrates the function and goes over the (few) options? That could use the data from http://www.fieldtriptoolbox.org/faq/what_types_of_datasets_and_their_respective_analyses_are_used_on_fieldtrip#meg-visuomotor275
which is on the ftp

E.g along these lines
```
cfg = [];
cfg.dataset = 'SubjectCMC.ds'
cfg.trl = ...

cfg.numclusters = 1;
grad1 = ft_headmovement(cfg)

cfg.numclusters = 2;
grad2 = ft_headmovement(cfg)

cfg.numclusters = 10;
grad10 = ft_headmovement(cfg);
```

and then check that the output grad is what you would expect (in terms of numcoils).

**Comment by Michelmann** [comment]
Dear Robert,
sorry for this very late reply. The dataset you recommended doesn't seem to have HLC channels. 
I tested the function with an own dataset (see below) and after fixing a typo it seems to work.
all the best,
Sebastian 

cfg = [];
cfg.dataset = data_set_;
cfg.trl = trl_used;

cfg.numclusters = 1;
grad1 = ft_headmovement(cfg)

cfg.numclusters = 2;
grad2 = ft_headmovement(cfg)

assert(size(grad2.tra,2) == 2*size(grad1.tra,2))

cfg.numclusters = 10;
grad10 = ft_headmovement(cfg)

assert(size(grad10.tra,2) == 10*size(grad1.tra,2))
processing channel { 'HLC0011' 'HLC0012' 'HLC0013' 'HLC0021' 'HLC0022' 'HLC0023' 'HLC0031' 'HLC0032' 'HLC0033' }
reading and preprocessing
reading and preprocessing trial 687 from 687

the call to "ft_preprocessing" took 40 seconds
the call to "ft_headmovement" took 43 seconds

grad1 = 

     balance: [1x1 struct]
     chanori: [299x3 double]
     chanpos: [299x3 double]
    chantype: {299x1 cell}
    chanunit: {299x1 cell}
     coilori: [589x3 double]
     coilpos: [589x3 double]
    coordsys: 'dewar'
       label: {299x1 cell}
         tra: [299x589 double]
        type: 'ctf275'
        unit: 'cm'

processing channel { 'HLC0011' 'HLC0012' 'HLC0013' 'HLC0021' 'HLC0022' 'HLC0023' 'HLC0031' 'HLC0032' 'HLC0033' }
reading and preprocessing
reading and preprocessing trial 687 from 687

the call to "ft_preprocessing" took 34 seconds
the call to "ft_headmovement" took 37 seconds

grad2 = 

     balance: [1x1 struct]
     chanori: [299x3 double]
     chanpos: [299x3 double]
    chantype: {299x1 cell}
    chanunit: {299x1 cell}
     coilori: [1178x3 double]
     coilpos: [1178x3 double]
    coordsys: 'dewar'
       label: {299x1 cell}
         tra: [299x1178 double]
        type: 'ctf275'
        unit: 'cm'

processing channel { 'HLC0011' 'HLC0012' 'HLC0013' 'HLC0021' 'HLC0022' 'HLC0023' 'HLC0031' 'HLC0032' 'HLC0033' }
reading and preprocessing
reading and preprocessing trial 687 from 687

the call to "ft_preprocessing" took 36 seconds
the call to "ft_headmovement" took 40 seconds

grad10 = 

     balance: [1x1 struct]
     chanori: [299x3 double]
     chanpos: [299x3 double]
    chantype: {299x1 cell}
    chanunit: {299x1 cell}
     coilori: [5890x3 double]
     coilpos: [5890x3 double]
    coordsys: 'dewar'
       label: {299x1 cell}
         tra: [299x5890 double]
        type: 'ctf275'
        unit: 'cm'

**Comment by anne-urai** [comment]
Any updates on this pull request? It would be great to solve this and make sure the ft_headmovement function works on all datasets.

**Comment by robertoostenveld** [comment]
Thanks. I updated the test script to a dataset that has HLC channels in it. I also added some sanity checks so that it gives a proper error when no HLC channels are present (now it failed in a weird way). I did some further updates as well, please have a look and let me know if you see room for other improvements.

**Pull request merged**
