### PR TITLE
Spm12 norm

### PR DESCRIPTION
**Pull request by schoffelen**

### CODE REVIEW

**Comment by schoffelen** [comment]
@jens-k @StolkArjen @stephenwhitmarsh I have made a start to implement the spatial normalisation as per spm12 (spmmethod='new');

It needs some testing still, and also it should still be extended to ft_warp_apply.
For the latter, it's again some 'prutsing', since the representation of the normalisation parameters differs across spm-versions, so the forward and backward warping of arbitrary point clouds needs to be done in a separate way. Feel free to pull this branch to your own computing environment and to test it

**Comment by jens-k** [comment]
It runs through for me (Win 7, Matlab 2015b). I tested it like this:

mri		= ft_read_mri('Subject01.mri');

cfg = [];
cfg.spmversion = 'spm12';
cfg.nonlinear = 'yes';
cfg.spmmethod = 'old';
old = ft_volumenormalise(cfg, mri);

cfg.spmmethod = 'new';
new = ft_volumenormalise(cfg, mri);

These are the original mri, the result with the old, and the new normalization.
image

**Comment by jens-k** [comment]
Ah and I still get the message "using 'OldNorm' normalisation" even when using spmmethod = new, because align_ctf2acpc is called at some point (which is a bit confusing).

**Comment by schoffelen** [comment]
Hi Jens, thanks for the feedback. I will look into the confusing warning. With respect to the comparison of the results: in terms of voxel dimensions the 'new brain' is much smaller than the old one. I didn't realize this, but it suggests as if the voxel size is 1.5 mm in that case?

**Comment by schoffelen** [comment]
OK, I think now the voxel size in the output will be correct

**Comment by jens-k** [comment]
Ok cool, thanks for that upgrade! One last thing. If I run the code the very first time, I get the following message (Windows 7, Matlab 2015b). We encountered that previously on Windows, it was about the files missing in external/smp12. However, the file is clearly there and if I run the exact same code again, the error is gone.

Undefined function or variable 'mysubs_fields'.

Error in cfg_item (line 101)
[fn, defs] = mysubs_fields;

Error in cfg_branch (line 86)
        gitem = cfg_item;

Error in cfg_getfile>reg_filter (line 1185)
    dprms  = {cfg_branch};

Error in cfg_getfile (line 177)
            t = reg_filter(varargin{2:end});

Error in spm_select (line 115)
            cfg_getfile('regfilter', 'mesh',  {'\.gii$'});

Error in spm_select (line 110)
            spm_select('regfilter');

Error in spm_select (line 97)
    spm_select('init');

Error in spm_platform>init_platform (line 233)
    driveLett = spm_select('ListDrives');

Error in spm_platform (line 62)
if isempty(PLATFORM), PLATFORM = init_platform; end

Error in spm_smoothto8bit>smoothto8bit (line 46)
VO.dt     = [spm_type('uint8') spm_platform('bigend')];

Error in spm_smoothto8bit (line 16)
    VO = smoothto8bit(V,fwhm);

Error in spm_normalise (line 157)
VF1 = spm_smoothto8bit(VF,flags.smosrc);

Error in align_ctf2acpc (line 174)
  params           = spm_normalise(V2,V1,[],[],[],flags);

Error in ft_convert_coordsys (line 104)
            obj = align_ctf2acpc(obj, opt);

Error in ft_volumesegment (line 307)
    mri = ft_convert_coordsys(mri, 'acpc');

**Comment by schoffelen** [comment]
I keep being surprised that SPM works at all...

I think I need to upgrade ft_convert_coordsys as well. Right now, it uses the 'OldNorm' functionality (as you already pointed out) for the Affine (approximate) coregistration of a 'ctf'-based volume to acpc space. I wonder whether your error goes away if everything is internally consistent, i.e.

either using the 'old-style' both for the coregistration and normalisation, or the 'new-style' for both steps.

**Comment by StolkArjen** [comment]
Seems the msg sent from my phone email inbox didn't come through. Anyway, in short, great initiative, and let me know when you want me to test this in the realm of intracranial EEG, warping electrodes (non-linearly) to a template brain (ft_volumenormalise followed by ft_warp_apply with the 'individual2sn' method).

**Comment by schoffelen** [comment]
Hi Arjen, I have implemented individual2sn, I think. It's a rather clunky implementation, and I am not fully sure whether it's correct, although the results look reasonable.

**Comment by schoffelen** [comment]
@jens-k reported error: it could also be that @cfg_item misses the mysubs_fields in its own private folder. It is present in @cfg_files/private. Perhaps adding the mysubs_fields in @cfg_item solves it.

**Comment by jens-k** [comment]
There is no cfg_files, I guess you meant @cfg_item there as well, right?

There is no @cfg_item/private though either.. I put mysubs_fields in the @cfg_item folder but that only changed the error into:

---
Undefined function or variable 'cfg_intree'.

Error in cfg_branch (line 92)
item = class(struct([]), myclass, gitem, cfg_intree);

Error in cfg_getfile>reg_filter (line 1185)
    dprms  = {cfg_branch};

Error in cfg_getfile (line 177)
            t = reg_filter(varargin{2:end});

Error in spm_select (line 115)
            cfg_getfile('regfilter', 'mesh',  {'\.gii$'});

Error in spm_select (line 110)
            spm_select('regfilter');

Error in spm_select (line 97)
    spm_select('init');

Error in spm_platform>init_platform (line 233)
    driveLett = spm_select('ListDrives');

Error in spm_platform (line 62)
if isempty(PLATFORM), PLATFORM = init_platform; end

Error in spm_smoothto8bit>smoothto8bit (line 46)
VO.dt     = [spm_type('uint8') spm_platform('bigend')];

Error in spm_smoothto8bit (line 16)
    VO = smoothto8bit(V,fwhm);

Error in spm_normalise (line 157)
VF1 = spm_smoothto8bit(VF,flags.smosrc);

Error in align_ctf2acpc (line 174)
  params           = spm_normalise(V2,V1,[],[],[],flags);

Error in ft_convert_coordsys (line 104)
            obj = align_ctf2acpc(obj, opt);

Error in ft_volumenormalise (line 127)
  mri = ft_convert_coordsys(mri, 'acpc');

--

I also put the file into @cfg_branch but also that didnt help. 

Sorry I dont have time to get deeper into it right now. I will try next week. How can it be that if you run the code a second time it works?

**Comment by StolkArjen** [comment]
screen shot 2017-11-04 at 3 46 14 pm

Left: SPM8, Right: SPM12, both non-linear warping using the default template.
So, can't wait to start using this for all data, cap! Note, by the way, that I had to use matlab v2015b in order to use spm8 (and its mexfiles).




Used code (and data from the human ecog tutorial):
fsmri_acpc = ft_read_mri('freesurfer/mri/T1.mgz')
fsmri_acpc.coordsys = 'acpc';
load('SubjectUCI29_elec_acpc_fr.mat')

cfg = [];
cfg.nonlinear = 'yes';
fsmri_mni = ft_volumenormalise(cfg, fsmri_acpc);

elec_mni_frv = elec_acpc_fr;
elec_mni_frv.elecpos = ft_warp_apply(fsmri_mni.params, elec_acpc_fr.elecpos, 'individual2sn');
elec_mni_frv.chanpos = ft_warp_apply(fsmri_mni.params, elec_acpc_fr.chanpos, 'individual2sn');
elec_mni_frv.coordsys = 'mni';

load([ftpath filesep 'template/anatomy/surface_pial_left.mat']);
ft_plot_mesh(mesh);
ft_plot_sens(elec_mni_frv);
view([-90 20]); material dull; lighting gouraud; camlight;

**Comment by schoffelen** [comment]
@StolkArjen looks nice! I think. Particularly the laminar probes not being bent gives the citizen courage, right?

**Comment by jens-k** [comment]
The odyssey won't end. I tried to one-by-one add the files asked for by the still occuring error messages on Windows 7. 

@cfg_leaf/cfg_leaf.m
@cfg_entry/cfg_entry.m 
@cfg_entry/private/mysubs_fields.m

At that point, spm_select('init') at line 120 tries to add frames.name to a non-structure object which leads to an error:
```
Reference to non-existent field 'name'.

Error in spm_select (line 120)
            frames.name    = 'Frames';
```
This only happens at the first try, though, because before the error is thrown the following code is executed:
```
persistent isInitSelect; 
isInitSelect = true;
```
The second time, isInitSelect is already true and spm_select('init') is never called.

I have no idea what this init procedure is for, but the code runs if I execute ``` persistent isInitSelect; isInitSelect = true; ``` myself before running ft_volumenormalise.

**Comment by schoffelen** [comment]
Boohoo! Could it be that you need the fieldnames.m and/or the subsasgn.m in the @cfg_entry directory?

**Comment by schoffelen** [comment]
Perhaps we should just add all these class definition directories (the ones starting with @cfg_) ...

**Comment by schoffelen** [comment]
@StolkArjen I think that I now have nailed the sn2individual and individual2sn conversion. Previously, it might have been incorrect. Much appreciated if you test on your own data.

**Comment by jens-k** [comment]
@schoffelen If I add those files it works for me:
https://github.com/schoffelen/fieldtrip/pull/4

(I tried to get rid of some of the @cfg folders but it's still alot of code..)

**Comment by schoffelen** [comment]
@jens-k thanks for your devotion in trying to nail this. I all of a sudden realize (while having a closer look at the errors), that Windows seems to choke in spm_normalise, which is in align_ctf2acpc. In other words, it is happening when you do the 'oldNorm' Affine alignment. Yet, it could be a coincidence that it happens just there, because maybe it's just the first time that this spm_select function is called. I was considering just merging your PR and leave it at that, but I am a bit unsatisfied with this (because it just adds quite a lot of junk to FT). 

With your permission, I'll first quickly check with Guillaume Flandin, to see whether he has a more elegant workaround for this

**Comment by StolkArjen** [comment]
@schoffelen: works great still, see

screen shot 2017-11-12 at 12 47 37 pm

Thanks a lot for this contribution. It looks to be very promising for intracranial EEG analyses, where the interpretation of template-based anatomy in individual subjects plays a significant role.

**Pull request merged**
