### PR TITLE
build in fileio support for the MEF format

### PR DESCRIPTION
**Pull request by schoffelen**
This is a trimmed down version of the original PR by @jiecui: #2379

### CODE REVIEW

**Comment by schoffelen** [comment]
Hi @jiecui, my suggestion would be to take it from here. I am currently trying (suffering) to get the Darkhorse stuff installed on our compute cluster, and combined with your toolbox, so that I can minimally test the functionality with your supplied test function. If that all works, I can proceed by making a scaffold page for the documentation, so that people can be instructed what to download (read_MEF and your toolbox + setup the mex files) so that they can get started themselves.

Does that sound like a plan?

**Comment by jiecui** [comment]
Hi @schoffelen, thank you so much for the effort! Sounds great! Please let me know if there is anything I can contribute. Just apologize in advance in case my response is slow.

**Comment by schoffelen** [comment]
do you know whether the source code for read_MED can be downloaded from somewhere?

**Comment by schoffelen** [comment]
I tried to read MED 1 files on my Mac, but also failed.... My current conclusion is that the code provided by darkhorse is not really robust.

**Comment by schoffelen** [comment]
I would like to move forward with this. At this stage I think that - as far as this PR is concerned - nothing needs to be done anymore. The following PRs still need work though:  https://github.com/fieldtrip/website/pull/771, and
https://github.com/jiecui/mef_reader_fieldtrip/pull/1

@jiecui I will merge this PR here for now, and hope that you will find some time soon to work on the other PRs

**Pull request merged**
