### PR TITLE
additional fix for yokogawa code (part of reading *.mrk )

### PR DESCRIPTION
**Pull request by KiwamuK**
We have changed Yokogawa code: 
If the input file does not contain marker-coil information, the code tries to read the *.mrk file with the same name as the input file.

### CODE REVIEW

**Comment by robertoostenveld** [comment]
Please note that there is a conflict. It seems that you have not been doing a "git pull" in between and that you are working with a (slightly) older version. @vlitvak (from the SPM team) made two small changes to the code in #725 and #728. 

I can easily merge this conflict in git. Please review the changes by changes. If they are OK with you, let me know.

**Comment by KiwamuK** [comment]
I have known that @vlitvak made small changes. 
I essentially leave for the changes made by him. The changes are OK.

**Comment by robertoostenveld** [comment]
thanks, I have merged it in the release

**Comment by KiwamuK** [comment]
Thanks!

**Pull request merged**
