### PR TITLE
ENH - changed some lines to prevent crash, let Roemer think about whe…

### PR DESCRIPTION
**Pull request by schoffelen**
…ther this is now resulting in desired behavior

### CODE REVIEW

**Comment by schoffelen** [comment]
This pertains to bug 3279. I understand the rationale in the code, but I don't know what the correct behavior in this case would be. Please review and fix if needed.

**Comment by schoffelen** [comment]
This still should be followed up.

**Comment by schoffelen** [comment]
Ach so. Wohin?

**Comment by roemervandermeij** [comment]
For the moment NL, afterwards, TBD!

**Comment by schoffelen** [comment]
Well, welcome back, and happy belated b-day!

**Pull request merged**
