### PR TITLE
ENH - use keepfields in the creation of tmpcfg, to pass on potentiall…

### PR DESCRIPTION
**Pull request by schoffelen**
…y defined spmversion

### CODE REVIEW

**Comment by schoffelen** [comment]
As a note for self:

[jansch@mentat001 fieldtrip]$ grep -l spmversion *.m
ft_prepare_headmodel.m
ft_prepare_mesh.m
ft_prepare_sourcemodel.m
ft_volumebiascorrect.m
ft_volumedownsample.m
ft_volumenormalise.m
ft_volumerealign.m
ft_volumesegment.m
ft_volumewrite.m

**Comment by schoffelen** [comment]
[jansch@mentat001 fieldtrip]$ grep -l spmversion */*.m
fileio/ft_write_mri.m
forward/ft_headmodel_interpolate.m
private/clusterstat.m
private/prepare_mesh_segmentation.m

**Comment by schoffelen** [comment]
[jansch@mentat001 fieldtrip]$ grep -l ft_prepare_mesh *.m
ft_prepare_headmodel.m
ft_prepare_layout.m
ft_prepare_mesh.m
ft_volumerealign.m

**Comment by TomRhysMarshall** [comment]
Hey JM,

Thanks for this. Let me know when/if it's helpful for me to test something.

**Comment by TomRhysMarshall** [comment]
Just pulled and tested and this is working now. Thanks a lot!

**Pull request merged**
