### PR TITLE
Adding compiled files for M1 Mac

### PR DESCRIPTION
**Pull request by arnodelorme**
This minor change would avoid a lot of confusion

### CODE REVIEW

**Comment by robertoostenveld** [comment]
Looking at the rather straightforward suggested change, the question to ask is: why are ft_definetrial and ft_redefinetrial separate functions? We don't have ft_prreprocessing and ft_repreprocessing either. What is your take on this @schoffelen? Should we perhaps consult the people in our MEG/EEG meeting?

**Comment by schoffelen** [comment]
confusion between ft_definetrial and ft_redefinetrial is indeed a recurring issue. Let's consult the local userbase.

**Comment by arnodelorme** [comment]
Added MAC silicon compiled files

**Comment by arnodelorme** [comment]
@robertoostenveld and @schoffelen based on discussion with Robert, I only kept the changes related to M1 Mac compiled files.

**Comment by robertoostenveld** [comment]
this was replaced by #2270

**Pull request closed without merging**
