### PR TITLE
fix correlation for time domain data

### PR DESCRIPTION
**Pull request by schoffelen**

### CODE REVIEW

**Comment by schoffelen** [comment]
This should fix it. @ruiliu-psy could you please check?

**Comment by ruiliu-psy** [comment]
> This should fix it. @ruiliu-psy could you please check?

Thanks for your quick response! This PR resolved the problem on raw data, but not another on computing the correlation.
https://github.com/fieldtrip/fieldtrip/issues/1656#issuecomment-767485405
Or maybe you might want to remove the method option 'corr'?

**Comment by schoffelen** [comment]
> > This should fix it. @ruiliu-psy could you please check?
> 
> Thanks for your quick response! This PR resolved the problem on raw data, but not another on computing the correlation.
> [#1656 (comment)](https://github.com/fieldtrip/fieldtrip/issues/1656#issuecomment-767485405)
> Or maybe you might want to remove the method option 'corr'?

I don't understand, adding the key-value pairs 'pownorm' = true, and 'complex' = 'complex'  (line 1037) ensures that ft_connectivity_corr returns a proper correlation coefficient.

**Comment by ruiliu-psy** [comment]
> I don't understand, adding the key-value pairs 'pownorm' = true, and 'complex' = 'complex' (line 1037) ensures that ft_connectivity_corr returns a proper correlation coefficient.

ah, sorry, the home fieldtrip has not yet got sync, I missed that part. yeah, it works perfectly, thank you!

**Pull request merged**
