### PR TITLE
implement signal quality index (SQI) algorithm for NIRS data

### PR DESCRIPTION
**Pull request by sofisappia**
Fieldtrip implementation of the [ Signal Quality Index (SQI) algorithm](https://github.com/Artinis-Medical-Systems-B-V/SignalQualityIndex/blob/master/SQI.m), published in [Biomedical Optics Express](https://doi.org/10.1364/BOE.409317). SQI assesses the signal quality of fNIRS signals and provides a continuous rating between 1 (very low signal quality) and 5 (very high signal quality). It can also be used as a binary rating of the signal quality by thresholding the output scores, as has been done in this implementation.

### CODE REVIEW

**Comment by robertoostenveld** [comment]
To ensure that this works now but also in the future on different versions of MATLAB, with different operating systems, and that it continues to work - also when we do code maintenance in the future  (aka https://en.wikipedia.org/wiki/Regression_testing) - I would like to have a small test script and data set to complement this. 

The data (which preferably is as small as possible, but large enough to make sense) should not be added to the repository, but see here https://www.fieldtriptoolbox.org/faq/how_should_i_send_example_data_to_the_developers/ 

The test script should be placed in `fieldtrip/test` and can follow the format of the many examples there. You don't have to bother with the `dccnpath` function, just write the script for a file in the present working directory. Once I have received the file and added it to our test directory own the compute cluster, I will update the script so that the code responsible for https://www.fieldtriptoolbox.org/development/testing/ will find it.

**Review by robertoostenveld — CHANGES_REQUESTED** [review]
To ensure that this works now but also in the future on different versions of MATLAB, with different operating systems, and that it continues to work - also when we do code maintenance in the future (aka https://en.wikipedia.org/wiki/Regression_testing) - I would like to have a small test script and data set to complement this.

The data (which preferably is as small as possible, but large enough to make sense) should not be added to the repository, but see here https://www.fieldtriptoolbox.org/faq/how_should_i_send_example_data_to_the_developers/

The test script should be placed in fieldtrip/test and can follow the format of the many examples there. You don't have to bother with the dccnpath function, just write the script for a file in the present working directory. Once I have received the file and added it to our test directory own the compute cluster, I will update the script so that the code responsible for https://www.fieldtriptoolbox.org/development/testing/ will find it.

**Comment by robertoostenveld** [comment]
`6c7ec2c/test_pull1751.txt:test_pull1751 FAILED in 13 seconds`

This** was expected. Can you send an `oxy3` format version of the same file?

**Comment by sofisappia** [comment]
> `6c7ec2c/test_pull1751.txt:test_pull1751 FAILED in 13 seconds`
> 
> This** was expected. Can you send an `oxy3` format version of the same file?

I just added the oxy3 file in the same drive folder.

**Pull request merged**
