### PR TITLE
adds fontsize to ft_plot_sens

### PR DESCRIPTION
**Pull request by ualsbombe**
Adds fontsize to ft_plot_sens

### CODE REVIEW

**Comment by robertoostenveld** [comment]
this assumes that the previous default was 10. I think that should be fine.

**Comment by robertoostenveld** [comment]
could you figure out what the "default" default would be, and whether the user can set another default that spans multiple figures? I.e. if you make a figure, what is the font size?

**Comment by ualsbombe** [comment]
```
fig = figure;
h = get(gca);
disp(h.FontSize)
```

This returns: 10, which I guess is the default then.

Changing the defaultaxesfontsize
```
set(0, 'defaultaxesfontsize', 30)
fig = figure;
h = get(gca);
disp(h.FontSize)
```

returns 30

So I guess the fontsize could be got from
`get(0, 'defaultextfontsize')`
Be aware that it is default_text_fontsize and not default_axes_fontsize that should be changed

**Comment by robertoostenveld** [comment]
```
get(0, 'defaultaxesfontsize')
```
works on 2016b and 2012b. It returns 10, which is consistent with documentation. I'll change it.

**Comment by ualsbombe** [comment]
I think it is `get(0, 'defaulttextfontsize')` you should use _not_ `get(0, 'defaultaxesfontsize')` since the text function is used to write the text.

**Pull request merged**
