### PR TITLE
ENH - prevent the use of the DSP toolbox in a test script

### PR DESCRIPTION
**Pull request by robertoostenveld**

### CODE REVIEW

**Comment by robertoostenveld** [comment]
As discussed with @ErikVanDenBoogert

**Comment by schoffelen** [comment]
shall we add my pinknoise function to fieldtrip?

**Comment by schoffelen** [comment]
Is it a licence issue?

**Comment by robertoostenveld** [comment]
I will run the full test batch once to see whether there is use of DSP functions elsewhere.

**Comment by robertoostenveld** [comment]
Yes, it is a license function. The RU only has two licenses, and our test script uses one of them (every night).  

The script now does
```
fn = cumsum(randn(1,length(t)));
```
to integrate random (white) noise and thereby create noise with a 1/f spectrum. If your function is smarter, feel free to use it instead. But if we want to make pink noise more broadly accessible, we better make it part of `ft_freqsimulation`.

**Comment by schoffelen** [comment]
No, it also has the cumsum trick, but if I recall well, it has also other 'method' to generate 1/f with different slopes

**Comment by robertoostenveld** [comment]
Let's remember that for later, but not spend time on it now.

**Comment by robertoostenveld** [comment]
The license is now not being used any more, even when I run all test scripts

```
roboos@mentat001> grep Signal_Blocks.*licenses 2021-03-19*
2021-03-19:00.04.02:Users of Signal_Blocks:  (Total of 2 licenses issued;  Total of 0 licenses in use)
2021-03-19:01.04.01:Users of Signal_Blocks:  (Total of 2 licenses issued;  Total of 0 licenses in use)
2021-03-19:02.04.01:Users of Signal_Blocks:  (Total of 2 licenses issued;  Total of 0 licenses in use)
2021-03-19:03.04.01:Users of Signal_Blocks:  (Total of 2 licenses issued;  Total of 0 licenses in use)
2021-03-19:04.04.02:Users of Signal_Blocks:  (Total of 2 licenses issued;  Total of 0 licenses in use)
2021-03-19:05.04.02:Users of Signal_Blocks:  (Total of 2 licenses issued;  Total of 0 licenses in use)
2021-03-19:06.04.01:Users of Signal_Blocks:  (Total of 2 licenses issued;  Total of 0 licenses in use)
2021-03-19:07.04.02:Users of Signal_Blocks:  (Total of 2 licenses issued;  Total of 0 licenses in use)
2021-03-19:08.04.02:Users of Signal_Blocks:  (Total of 2 licenses issued;  Total of 0 licenses in use)
2021-03-19:09.04.01:Users of Signal_Blocks:  (Total of 2 licenses issued;  Total of 0 licenses in use)
```

**Pull request merged**
