### PR TITLE
ENH - add referential marker in ortho if input has meaningful coordsys

### PR DESCRIPTION
**Pull request by schoffelen**

### CODE REVIEW

**Comment by schoffelen** [comment]
Screenshot 2022-03-09 at 13 08 11
Screenshot 2022-03-09 at 13 09 25
Screenshot 2022-03-09 at 13 09 55

**Comment by schoffelen** [comment]
Mr Potatoman to the next level. It seems to work OK. Please shoot at it.

**Comment by robertoostenveld** [comment]
So what I understand is that you 

1. turn it so that xyz is close to ijk.
2. add L and R to the appropriate subplots

right? 

It looks good to me.

**Comment by schoffelen** [comment]
> So what I understand is that you
> 
> 1. turn it so that xyz is close to ijk.
> 2. add L and R to the appropriate subplots
> 
> right?

yep

**Review by robertoostenveld — APPROVED** [review]
let's merge this.

**Pull request merged**
