### PR TITLE
Improve JOSS formatting

### PR DESCRIPTION
**Pull request by matsvanes**
- Reformatted the code snippets to span multiple lines when too long
- removed some of MVE's funding (i.e., they were irrelevant)
- cleaned up .bib file

### CODE REVIEW

**Review by robertoostenveld — APPROVED** [review]
looks fine to me

**Comment by matsvanes** [comment]
@robertoostenveld I think I've foolishly sent the PR's for main branch, while we created a JOSS branch specifically for the review - and I think JOSS is automatically building the paper from the JOSS branch as well (see https://github.com/openjournals/joss-reviews/issues/5566#issue-1760892414). I think previously the argument was that preferably the main branch would stay "clean". 
Ergo, should we revert this and pull into the JOSS branch instead?

**Comment by robertoostenveld** [comment]
oops. I'll merge the commits also into the JOSS branch, just give me a few hours or so.

**Comment by robertoostenveld** [comment]
I have done  `git reset --hard HEAD~` which removes the last commit. Then I force-pushed it to gitlab, bitbucket and gitlab. People who have pulled from fieldtrip/fieldtrip in the last 3 hours will have the commit on their local version.  I think that the chance for that is quite small.

Can you make a new PR from your matsvanes:patch8 branch to the JOSS branch?

**Pull request merged**
