### PR TITLE
Additional files to make ft_volumesegment work on windows

### PR DESCRIPTION
**Pull request by jens-k**

### CODE REVIEW

**Comment by schoffelen** [comment]
as you mentioned in our other conversation, perhaps it's better to move it down, to stay consistent with spm main, to @cfg_branch

**Comment by jens-k** [comment]
Sorry, I tried to put it in the folder @cfg_branch but the github webinterface dropped the @. In the meanwhile github desktop takes forever and constantly gives me errors. Seems I gotta completely reset my local repository..

Could you add the @?

**Comment by schoffelen** [comment]
sure, I'll try.

**Comment by schoffelen** [comment]
Done, I think

**Comment by jens-k** [comment]
Looks good!
Thanks for the effort and all the new stuff!

**Pull request merged**
