### PR TITLE
Added spm12's new cfg_getfile

### PR DESCRIPTION
**Pull request by jens-k**
See comment to #376

### CODE REVIEW

**Comment by schoffelen** [comment]
Oh no,  ~1500 lines of additional code, just to get it running on windows.

**Comment by schoffelen** [comment]
Hi Jens, 
I don't get it: if cfg_getfile is called by spm_select, how come this does not crash higher up? spm_select is not in external/spm12

**Comment by jens-k** [comment]
Good point. I had an unneccessary function call in my test script that added spm8 to the path (so external/spm8/spm_select was called which chokes on 'ListDrives' as input). Seems another 100 lines of code for spm_select will be needed to support windows. Totally worth it ;)

A - not very clean - alternative would be to write our own function that handles exactly this one call.

**Comment by schoffelen** [comment]
thanks

**Pull request merged**
