### PR TITLE
ENH - update the channel position, weighted with the montage (it used…

### PR DESCRIPTION
**Pull request by robertoostenveld**
… to be changed to nan). See http://bugzilla.fieldtriptoolbox.org/show_bug.cgi?id=3229

### CODE REVIEW

**Comment by robertoostenveld** [comment]
@schoffelen can you review this one?

**Comment by schoffelen** [comment]
oh nee, moet 'k 11 files doorploegen :o(

**Comment by robertoostenveld** [comment]
misschien will @StolkArjen hem wel even reviewen. Die is toch klaarwakker...

**Comment by schoffelen** [comment]
nee hoor, ik kijk wel even.

**Comment by schoffelen** [comment]
Just a naive question; as per the bug the averaging of positions makes sense, but in the case of more funky tra-matrices it doesn't (e.g. components). I don't quickly see whether this distinction is made.

**Comment by robertoostenveld** [comment]
for cleaning of ICA components, the channel names remain the same, which affects line 380 (keepchans=yes). In cases where channel names do not stay the same, keepchan=no and the chanpos is recomputed. 

It is an interesting test case to consider a ft_componentanalysis with method=pca, and then ft_rejectcomponent without rejecting anything, but back projecting the components...

**Comment by robertoostenveld** [comment]
I added a section to the test script. But cannot get it to work, since the initial balancing is not present to start with, and I don't know where it should be added. The test script actually reveals an error in the balance bookkeeping. @schoffelen could you have a look at the last section of the test script?

**Comment by schoffelen** [comment]
will do. Domani...

**Comment by StolkArjen** [comment]
elec.label = {'1';'2';'3';'4'};
elec.elecpos = [1 1 1; 2 2 2; 3 3 3; 4 4 4];
elec.chanpos = elec.elecpos;
elec.tra = eye(4);

bipolar.labelold  = {'1', '2', '3', '4'};
bipolar.labelnew  = {'1-2', '2-3', '3-4'};
bipolar.tra       = [
  +1 -1  0  0
   0 +1 -1  0
   0  0 +1 -1
  ];

posweight = abs(bipolar.tra);
posweight = diag(1./sum(posweight,2)) * posweight;

elec.chanpos = posweight * elec.chanpos
produces the expected result:

    1.5000    1.5000    1.5000
    2.5000    2.5000    2.5000
    3.5000    3.5000    3.5000

Wondering whether the same posweight matrix should also be used for (bipolar) derivation of the neural data? line 495 in ft_apply_montage: (data.trial{i} = montage.tra * data.trial{i};)

**Comment by robertoostenveld** [comment]
> Wondering whether the same posweight matrix should also be used for (bipolar) derivation of the neural data?

No. The bipolar channel is the difference between two electrodes, which involves a minus. The bipolar position  is an average of two electrode positions, which involves a plus (and a 1/2).

**Comment by StolkArjen** [comment]
Makes sense. Grazie.

**Comment by robertoostenveld** [comment]
I made the overall handling of ft_apply_montage and the sense.balance field more consistent. It is still not perfect, but should be better. I think my work is complete now.

This also addresses http://bugzilla.fieldtriptoolbox.org/show_bug.cgi?id=1481, http://bugzilla.fieldtriptoolbox.org/show_bug.cgi?id=1990 and http://bugzilla.fieldtriptoolbox.org/show_bug.cgi?id=2634.

I ran some test, not all. @schoffelen, do you care to test more elaborately, or should we just merge and see whether the code holds up to the stress of actual use? If any, there will be only (obvious) bookkeeping errors, no numerical errors.

**Comment by robertoostenveld** [comment]
@StolkArjen, please note that when doing ft_componentanalysis and then ft_rejectcomponent, you will also get weird mixtures of channel positions. I.e. the original channel position will not be retrieved. This is technically correct, but may be undesired. For that purpose you should use the cfg.updatesens=yes/no option, i.e. default=yes, but if you don't want the sense to change, specify no.

**Comment by schoffelen** [comment]
Let me read through the changes, I should probably not devote too much time now to extensive testing.

**Comment by schoffelen** [comment]
Looks good to me. God zegene de greep!

**Comment by StolkArjen** [comment]
Thanks @robertoostenveld, nice work

**Pull request merged**
