### PR TITLE
fix: ft_qualitycheck no longer was able to access the filename in a s…

### PR DESCRIPTION
**Pull request by StolkArjen**
…ubfunction

the issue was described in https://github.com/fieldtrip/fieldtrip/issues/623

### CODE REVIEW

**Comment by schoffelen** [comment]
Out of curiosity, why does this change fix an issue? If I read the edit to the file, the only change occurred within a try-part of a try-catch statement, which would silently go to the catch part, if an error is encountered. Also, I am not sure whether the low-level field ...hdr.orig.FileName exists for every type of file in the input.

**Comment by StolkArjen** [comment]
The catch part only works for meg given that the headpos variable does not exist / is empty for eeg datatypes. Hmm, the hdr.orig.filename existed for test data, but if you think it’s not a given, we’ll need to come up with another way of retrieving the cfg.dataset input. Any suggestions? This used to be in timelock.cfg.dataset but apparently no longer.

**Comment by schoffelen** [comment]
I see. Well,  I haven't looked into this, but you changed timelock.cfg.dataset into info.hdr.orig.FileName, and I am not so sure whether this is more robust in general. 
It feels to me that in order to make these lines fully robust, we would need the equivalent of a double try/catch. In general, an error would occur, if a particular field does not exist in the input argument to filetyper, right? Why not do something like this:

if isfield(timelock.cfg,'dataset'),
filename = timelock.cfg.dataset;
elseif isfield(info.hdr.orig, 'FileName')
filename = info. blabla
elseif some other conditional statement
elseif some even other conditional statement
else
error('could not determine the filename');
end
[ ] =filetyper(filename);


Moet jij trouwens niet gaan slapen, of ben je in Europa?

**Comment by StolkArjen** [comment]
Gracias for this suggestion. Also added another field to info (info.filename) to make the extraction of filename information futureproof.

**Comment by StolkArjen** [comment]
En ja, 't was een latertje. ;)

**Comment by schoffelen** [comment]
wil je de comment in de code nog veranderen? (van january 2017 naar january 2018), of zal ik maar mergen?

**Comment by StolkArjen** [comment]
Oh hahah, hang on

**Comment by schoffelen** [comment]
check!

**Pull request merged**
