### PR TITLE
finish the implementation for support of PLM as connectivity metric 

### PR DESCRIPTION
**Pull request by schoffelen**
This PR combines patch-5 and patch-6, which were submitted by @fabiobaselice, into a single PR

### CODE REVIEW

**Comment by schoffelen** [comment]
This relates to #1638 and #1635

**Comment by schoffelen** [comment]
I will close the abovementioned PRs, and suggest to continue working in this PR, to keep things together (and to have an informative name of the branch)

**Comment by schoffelen** [comment]
OK, this is probably not going to work well, due to permission problems.
Since  I'd like @fabiobaselice to do the actual work, I will be closing this one again. Please submit your test function into either #1638 or #1635 (ideally try and combine these PRs into a single PR -> https://stackoverflow.com/questions/14391421/merging-pull-requests-together), and we take it from there.

**Comment by fabiobaselice** [comment]
> OK, this is probably not going to work well, due to permission problems.
> Since I'd like @fabiobaselice to do the actual work, I will be closing this one again. Please submit your test function into either #1638 or #1635 (ideally try and combine these PRs into a single PR -> https://stackoverflow.com/questions/14391421/merging-pull-requests-together), and we take it from there.

I can't merge the PRs. Maybe again permission problems? (From the github documentation: "To merge pull requests, you must have write permissions in the repository")

**Comment by schoffelen** [comment]
I know that you cannot merge, but you should be able to push to your own PR, which would make life easier on our end. Alternatively, I can just reopen the PR that I created this morning, and merge it, and then wait for your test code in a new PR

**Comment by fabiobaselice** [comment]
The second solution is the optimal one for me.....

**Comment by schoffelen** [comment]
I was afraid that you would say this.

**Comment by schoffelen** [comment]
I have now added a small snippet of test code, and have updated the functions such that it generates output according to fieldtrip's convention. The ball is back in your court with respect to improving the test code and writing some documentation

**Pull request merged**
