### PR TITLE
add feedback about tissue compartment volume

### PR DESCRIPTION
**Pull request by schoffelen**

### CODE REVIEW

**Comment by schoffelen** [comment]
@mcpiastra could you have a look whether this makes sense?

With this PR, through ft_checkdata, which goes through ft_datatype_segmentation if appropriate, the volumes of the tissue compartments are estimated and printed on the screen.

**Comment by robertoostenveld** [comment]
"botshaft" 😆

looks good to me. Do you want me to execute the code on my own computer to see if it runs?

**Comment by schoffelen** [comment]
yeah, that's ok, but it works on my end on segmentedmri from subject01

**Comment by mcpiastra** [comment]
I will run it on my pc asap. 
@schoffelen how much CSF do you get?
I was recently checking literature and found that "The mean CSF volume is 150 ml, with 25 ml in the ventricles and 125 ml in subarachnoid spaces." (https://doi.org/10.1016/j.anorl.2011.03.002)

**Comment by mcpiastra** [comment]
this is how I usually visualize a segmentation (`segm_5c`):
`seg_i = ft_datatype_segmentation(segm_5c,'segmentationstyle','indexed');`

`cfg              = [];`
`cfg.funparameter = 'seg';`
`cfg.funcolormap  = gray(6); % distinct color per tissue`
`cfg.location     = 'center';`
`cfg.atlas        = seg_i;`
`ft_sourceplot(cfg, seg_i);`

now the volumes of the compartments are printed 3 times:
- 1 when calling `seg_i = ft_datatype_segmentation(segm_5c,'segmentationstyle','indexed')` (useful)
- 2 when calling  `ft_sourceplot(cfg, seg_i);` (redundant?)

so far I saw why this is happening, but I am not sure how to fix this, nor if it is bothering. 
ps. is it good to keep writing here?

**Comment by robertoostenveld** [comment]
Hi Maria-Carla

with #1459 I have made some changes to the feedback that is given for segmentations. The code moved from `ft_datatype_segmentation` to `ft_checkdata` for feedback consistency, it shows it both when unit is available (as milliliter to make it more interpretable, i.e. cm^3) and when not available (as voxels), it now works for probabilistic segmentations, and some other improvements. 

I have not checked in which high-level FT functions it would now print it at the start (I would expect ft_prepare_mesh, or ft_prepare_headmodel), but you can also triger it yourself with `ft_checkdata(segmentation, 'feedback', 'yes')`.

Can you check whether the new code (now on the master branch) works for you?

cheers
Robert

**Comment by mcpiastra** [comment]
hi Robert,
with the new code the volumes in ml (and %) are printed only once, when calling
`ft_sourceplot(cfg, seg_i);` (see above).
I will check with other high-level FT functions asap.
best,
MC

**Pull request merged**
