### PR TITLE
improve the layout generation to deal with ECoG and sEEG

### PR DESCRIPTION
**Pull request by robertoostenveld**
@roemervandermeij and @StolkArjen 

This PR supersedes the #335 and focusses on backward compatibility. The test script does not yet deal with automatic generation of the layout for intracranial electrodes, but some of the related options have been tested and confirmed to work with EEG and MEG.

### CODE REVIEW

**Comment by robertoostenveld** [comment]
ok, this addresses part of the challenge of http://bugzilla.fieldtriptoolbox.org/show_bug.cgi?id=3059. Please see the test script and data on ftp:://ftp.fieldtriptoolbox.org/pub/fieldtrip/tutorial/layout.

I can now do 

```
lh = load('SubjectUCI29_cortex_lh');
rh = load('SubjectUCI29_cortex_rh');
elec = ft_read_sens('SubjectUCI29_elec_tal_f.mat');

% shift it a bit, otherwise it seems too high (!?)
elec.chanpos(:,3) = elec.chanpos(:,3) - 5;
elec.elecpos(:,3) = elec.elecpos(:,3) - 5;

figure
ft_plot_sens(elec, 'label', 'label')
ft_plot_mesh(lh.mesh);
ft_plot_mesh(rh.mesh);
camlight

cfg = [];
cfg.elec = elec;
cfg.projection = 'orthographic';

cfg.headshape = lh.mesh;
cfg.channel = 'LP*';
cfg.viewpoint = 'left';
cfg.mask = 'convex';
layout = ft_prepare_layout(cfg);
figure; ft_plot_lay(layout); title(cfg.viewpoint)

cfg.headshape(1) = lh.mesh;
cfg.headshape(2) = rh.mesh;
cfg.channel = {'LA*', 'LH*', 'RO*', 'RT*'};
cfg.viewpoint = 'inferior';
cfg.mask = 'none';
layout = ft_prepare_layout(cfg);
figure; ft_plot_lay(layout); title(cfg.viewpoint)
```

and get this 
screen shot 2017-03-23 at 17 07 02

screen shot 2017-03-23 at 17 07 05

screen shot 2017-03-23 at 17 07 08

note that the last is seen from inferior, i.e. radiological convention.

**Comment by StolkArjen** [comment]
Nice! Are the sizes of the TFRs in the multiplots automatically determined, or maybe configurable?

screen shot 2017-03-23 at 11 20 39 am

**Comment by StolkArjen** [comment]
p.s. Robert, you used elec_tal_f instead of elec_tal_fr (realigned to the cortex hull). There's also an elec_tal_fm btw (reMontaged - i.e. bipolar).

**Comment by roemervandermeij** [comment]
@StolkArjen 
For this, there's the option cfg.boxchannel, which for ECoG should be the same as cfg.channel (i.e. only the channels you are plotting right there). This determines which channels (and their 2D distances are used to determine the size of the boxes

**Comment by StolkArjen** [comment]
@robertoostenveld: of course, why doesn't it surprise me you guys had already thought of that!

**Comment by StolkArjen** [comment]
Encountered an issue with the depth electrodes, that didn't occur with the grids. When clicking in the TFR, the topoplot pop-up shows the contour only, thus without the data. Any idea why? I ensured all depths were inside the layouts (some of them were outside before).

screen shot 2017-03-23 at 11 44 06 am





load('SubjectUCI29_freq.mat', 'freq');
cfg               = [];
cfg.baseline 	    = [-.3 -.1];
cfg.baselinetype  = 'relchange';
freq_blc = ft_freqbaseline(cfg, freq);

load('SubjectUCI29_elec_tal_fm.mat')
cortex_lh = load('SubjectUCI29_cortex_lh');
cortex_rh = load('SubjectUCI29_cortex_rh');

cfg = [];
cfg.projection = 'orthographic';
cfg.elec = elec_tal_fm;
cfg.headshape(1) = cortex_lh.mesh;
cfg.headshape(2) = cortex_rh.mesh;
cfg.channel = {'LAM1-LAM2', 'LHH1-LHH2', 'LTH1-LTH2', 'RAM1-RAM2', 'RHH1-RHH2', 'RTH1-RTH2'};
cfg.viewpoint = 'superior';
cfg.mask = 'none';
layout2 = ft_prepare_layout(cfg);
figure; ft_plot_lay(layout2); title(cfg.viewpoint)

cfgp = [];
cfgp.layout = layout2;
ft_topoplotTFR(cfgp, freq_blc)

**Comment by StolkArjen** [comment]
Further checking: Even specifying just three electrodes in the left hemisphere for the layout doesn't produce a topoplot.



cfg = [];
cfg.projection = 'orthographic';
cfg.elec = elec_tal_fm;
cfg.headshape(1) = cortex_lh.mesh;
cfg.headshape(2) = cortex_rh.mesh;
cfg.channel = {'LAM1-LAM2', 'LHH1-LHH2', 'LTH1-LTH2'};
cfg.viewpoint = 'superior';
cfg.mask = 'none';
layout2 = ft_prepare_layout(cfg);
figure; ft_plot_lay(layout2); title(cfg.viewpoint)

cfgp = [];
cfgp.layout = layout2;
figure; ft_topoplotTFR(cfgp, freq_blc)

screen shot 2017-03-23 at 11 47 23 am

**Comment by roemervandermeij** [comment]
In these situations, I think topo's require a mask, right? What if you set cfg.mask = convex?

**Comment by StolkArjen** [comment]
Oh, that works indeed. Thanks.

screen shot 2017-03-23 at 12 19 23 pm

**Comment by roemervandermeij** [comment]
Good! 

For depths, I think the following would be more useful though:

```matlab
% generate anatomical layout, and then multiplot freq with the anatomical as a central layout with depths belongsides it
% in individual layouts
% first generate anatomical layout
depthnames = {'RAM*','RHH*','RTH*','ROC*','LAM*','LHH*','LTH*'};
cfg = [];
cfg.elec        = elec_tal_fm;
cfg.channel     = depthnames;
cfg.projection  = 'orthographic';
cfg.viewpoint   = 'superior';
cfg.headshape(1)   = cortex_lh.mesh;
cfg.headshape(2)   = cortex_rh.mesh;
cfg.skipscale   = 'yes';
cfg.skipcomnt   = 'yes';
anatlay = ft_prepare_layout(cfg);
% plot all, with the anatomical in the center
figure('numbertitle','off','name','depth freq');
subplot(3,3,5)
ft_plot_lay(anatlay,'box',false,'mask',false,'labelselect',5);
for idepth = 1:numel(depthnames)
  ind = idepth+(idepth>=5);
  subplot(3,3,ind)
  cfg = [];
  cfg.layout       = '5column'; % horizontal
  cfg.channel      = depthnames{idepth};
  cfg.baseline     = [-3 0];
  cfg.baselinetype = 'relchange';
  cfg.showoutline  = 'yes';
  cfg.showlabels   = 'no';
  cfg.showscale    = 'no';
  cfg.showcomment  = 'no';
  ft_multiplotTFR(cfg,freq);
  title(depthnames{idepth}(1:end-1))
end

```


Two 'problems' remain here:
1) labels on the central layout suck
2) the labels on each electrode suck 

Number 2 can be solved 'relatively' easily, by implementing an option for labelboxtitle in ft_plot_lay, which is passed from ft_topoplotTFR/etc as cfg.showlabels = 'yes'/'no'/'boxtitle', where box refers to the plotting box around the electrode.
Number 1 is more difficult, I've played around with some things, but no good solution found yet.

**Comment by StolkArjen** [comment]
Really cool. I don't think it matters a lot the labels aren't super crisp. The point is to be able to do fast browsing through the neural data, rather than 'data communication'.

**Comment by robertoostenveld** [comment]
please note that I made some changes (i.e. improvements and bug fixes) to the code. The previous version would not always add a mask/outline to the layout, now it does. There is now also Nrow (with N from 1-9), as there is also Ncolumn as layout style (e.g. cfg.layout='2row').

**Pull request merged**
