### PR TITLE
recompiled mexmaci64 binaries for spm8, spm12 and bci2000

### PR DESCRIPTION
**Pull request by abush84**
I had to recompile the MEX files to be able to go through the ECoG tutorial (http://www.fieldtriptoolbox.org/tutorial/human_ecog) on macOS 10.12.6, and to open BCI2000 files.

### CODE REVIEW

**Comment by StolkArjen** [comment]
Hi Alan,
Can you provide an example of how this failed for you? I've been using the procedure on that wiki page, as well as that described in a separate (unpublished) protocol that I emailed to your Pittsburgh account, without any mex-file related issues for some time already. On a possibly related note, I did encounter issues with spm8 mexfiles when using MATLAB2017b, which were resolved by forcing the use of spm12.

**Comment by abush84** [comment]
Hi Stolk,

I got the protocol, but haven't gone through it yet. When running the [tutorial](http://www.fieldtriptoolbox.org/tutorial/human_ecog) I got up to the line

```
% write to file, for later processing
ft_write_mri('SubjectUCI29_MR_preproc.nii', mri.anatomy, 'transform', mri.transform, 'dataformat', 'nifti_spm');
```

and got the following error

```
Invalid MEX-file '/Users/brainmodulationlab/git/fieldtrip/external/spm8/spm_existfile.mexmaci64':
dlopen(/Users/brainmodulationlab/git/fieldtrip/external/spm8/spm_existfile.mexmaci64, 6): Library not loaded: @loader_path/libmex.dylib
  Referenced from: /Users/brainmodulationlab/git/fieldtrip/external/spm8/spm_existfile.mexmaci64
  Reason: image not found.
```

I'm using Matlab 2017b on macOS 10.12.6. Trying to reproduce this error I just realized I forgot to include two more .macmexi64 files in my PR. 

fieldtrip/external/spm8/@file_array/private/file2mat.mexmaci64
fieldtrip/external/spm8/@file_array/private/mat2file.mexmaci64

Alan

**Comment by StolkArjen** [comment]
Hi Alan,
Sounds exactly like the issue I ran into while updating to v2017b a week ago. Thanks for recompiling the mex files - will discuss with @robertoostenveld and @schoffelen whether we decide to update the 'external' files ourselves or not. In the meantime, could you try and specify cfg.spmversion = 'spm12' when calling ft_volumewrite (the higher-level equivalent of ft_write_mri, see our recommendations in the protocol). The spm12 mex files worked for me, but if they're not working for you either, please let us know by reporting back.
Best regards, Arjen

**Comment by abush84** [comment]
Yes, using spmversion = 'spm12' solves the problem. 

```
% co-register the CT to the MRI
cfg             = [];
cfg.method      = 'spm';
cfg.spmversion  = 'spm12';
cfg.coordsys    = 'tal';
cfg.viewresult  = 'yes'; % view realignment result
ct = ft_volumerealign(cfg, ct, mri);

% write to file, as a backup
ft_write_mri('SubjectUCI29_CT_coreg.nii', ct.anatomy, 'transform', ct.transform, 'dataformat', 'nifti_spm','spmversion','spm12');
```

Maybe it would be a good idea to add the ft_write_mri(___,'spmversion','spm12') option in the tutorial... or maybe define it as the default option?

I also included recompiled MEX files for BCI2000, as I had the same kind of problem when loading those files.

**Comment by StolkArjen** [comment]
Good to hear. The protocol is going to replace the tutorial in the near future, so I'd stick to the protocol for now. Spm12 has been almost fully integrated but not entirely, so we cannot change the default across the board of functionalities. However, in order to use spm12 as much as possible, a tip from Robert is to add the following to your startup.m (if you have one):

global ft_default
ft_default.spmversion = 'spm12'
ft_defaults % this loads the rest of the defaults

That way spm12 is your default spm version in fieldtrip. Thanks for the BCI2000 mex files. Why did you also recompile the spm12 mex files, btw? Those are fine, aren't they, or did you encounter any issues with them in v2017b as well?

**Comment by robertoostenveld** [comment]
the load_bcidat.mexmaci64 mex file is not used in that tutorial, right?

Whenever someone recompiles with 
1) a new version of MATLAB
2) a new version of the operating system
3) a new version of the compiler or of the system libraries
the binary mex files will change. 

Please check http://www.fieldtriptoolbox.org/development/guidelines/code#ensure_that_it_runs_on_older_matlab_versions
and
http://www.fieldtriptoolbox.org/development/guidelines/code#compiling_mex_files

Updated mex files will not be merged, unless tested on a MATLAB version of at least 5 years old.

**Comment by abush84** [comment]
I think at some point I got a Invalid MEX-file message for spm12, but on a quick run can't reproduce it now.

**Comment by abush84** [comment]
load_bcidat.mexmaci64  is not used in the tutorial, had to recompile to be able to load BCI2000 files.

**Pull request closed without merging**
