### PR TITLE
freqanalysis: use parfor instead of for

### PR DESCRIPTION
**Pull request by AljenU**
For this function, using parfor does appear to be useful. The timing information gathered on some testfunctions does show improvement (https://github.com/fieldtrip/fieldtrip/issues/1853#issuecomment-1220758118), and this is also confirmed by the profiling reports.

This function also shows that sometimes, quite some work is needed to enable changing a for loop to a parfor loop.

Note that for now only the keeprpt cases 1 and 2 have a parfor loop, the case 4 is still a regular for loop. This because the case 4 indexes into the output in a way that is not compatible with parfor. Refactoring that case to use parfor could also be done, but it would use a lot more temporary memory.

### CODE REVIEW

**Comment by robertoostenveld** [comment]
Hi @AljenU,

Following [this](https://github.com/fieldtrip/fieldtrip/projects/5#card-85780402), can you change the branch for this pull request following [this documentation](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request).

And can you do the same for PR #2068 and #2069 ? I will then merge them all. 

thanks,
Robert

**Comment by AljenU** [comment]
> Hi @AljenU,
> 
> Following [this](https://github.com/fieldtrip/fieldtrip/projects/5#card-85780402), can you change the branch for this pull request following [this documentation](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request). It should point to the [parallel](https://github.com/fieldtrip/fieldtrip/tree/parallel) branch, which ar this moment is still in perfect sync with the master branch.
> 
> And can you do the same for PR #2068 and #2069 ? I will then merge them all.
> 
> thanks, Robert

@robertoostenveld Done

**Comment by robertoostenveld** [comment]
thanks!

**Comment by robertoostenveld** [comment]
There are still a few things on https://github.com/fieldtrip/fieldtrip/projects/5 to be done by us (i.e. @schoffelen and me), mainly regarding documentation and updating the README on the parallel branch.

**Pull request merged**
