### PR TITLE
ENH – optimization regarding runtime

### PR DESCRIPTION
**Pull request by dmatthes1982**
Function ft_fetch_data – ENH optimization regarding runtime. The zeros-function needed a lot of time in case of large dataset and allocated a lot of memory, which afterwards was never used.

### CODE REVIEW

**Comment by dmatthes1982** [comment]
In addition to this change I have a second question: This function is always running into the if case in the "get the options"-section, but the else path is a little faster. Why do you always prefer the if case?

**Comment by schoffelen** [comment]
The code looks good (from reading), Daniel. Can you confirm that you have ensured that the behaviour of the function has not changed?

**Comment by robertoostenveld** [comment]
please use the `test_ft_fetch_data.m` script, which you can find in fieldtrip/test

**Comment by dmatthes1982** [comment]
Thanks for your hint @robertoostenveld. I found a mistake and I will fix it as soon as possible.

**Comment by dmatthes1982** [comment]
Now, test_ft_fetch_data quits says only

avg. #samples: 1199.00 +/- 0.00
Elapsed time is 3.533915 seconds. 

It seems to work.

**Comment by robertoostenveld** [comment]
I had not looked into the script and I did not know that the test script was mainly for speed. It would actually be interesting to know how fast it was prior to your change. 

Furthermore, since `test_ft_fetch_data.m` does not  test many different cases, could you please also test these other scripts:

```
mac011> grep -l ft_fetch_data *
grep: private: Is a directory
test_bug1667.m
test_bug1735.m
test_bug2269.m
test_bug3267.m
test_bug3379.m
test_ft_fetch_data.m
test_issue968.m
test_pull810.m 
```

and see which ones you could also test? Some of them will be reading data from disk, which you don't have and therefore cannot test. But some of them are with simulated data in memory.

**Comment by dmatthes1982** [comment]
Today, I checked the performance increase. The script ft_test_fetch_data shows no significant improvement. Before the change, it says 3.87 sec. After the change it says 3.77 sec.

But I have a dataset with a length of 71 Minutes, consisting of 25 trials each with a duration of around three minutes. I want to subsegment these trials into subtrials with a length of 1 second and by creating an overlap of 50%. When I now run ft_redefinetrial, which calls ft_fetch_data, the computation time is ca. 45 seconds before changing the code and 4.6 seconds afterwards. In a later step I'm additionally running ft_rejectartifact on the subsegmented data. Here a got at least an improvement from 166 seconds to 97 seconds. So this change in ft_fetch_data helps me a lot.

I will test the other scripts in the following days and keep you updated.

**Comment by robertoostenveld** [comment]
thanks for testing the speed. 

Good that it did not get slower;  since that is what I am worried about: that the implementation can be optimized for one use-case, but subsequently gets worse for another use case.  

Please do also test the others (at least the ones you can test without having the data)

**Comment by robertoostenveld** [comment]
Since it does not get slower in the test scripts, and does get faster in your specific case, I consider it a general improvement.  I tested the whole batch of test scripts against your pull request, all tests work fine.

**Pull request merged**
