### PR TITLE
Bugfix: hascolor

### PR DESCRIPTION
**Pull request by StolkArjen**

### CODE REVIEW

**Comment by roemervandermeij** [comment]
Arjen, one of your commits included ft_intracranplotER. Please remove this! I develop it in a separate branch. 

Also, since it's in your master, I think something went wrong with your fork. Something awful :p. Oh no no no no no no, a lot of these are commits that have already been committed and pulled in. Something went bad Arjen. Real bad :o

**Comment by roemervandermeij** [comment]
Do you remember what specific thing you want to pull into fieldtrip:master? 

If so, this can be cleaned up. 

All of these merge branch master commits should not have been commits.

**Comment by roemervandermeij** [comment]
How it happened is beyond me :P.

Since that only change is the hascolor though, the solution is easy :). 

1) copy your updated version of ft_electrodeplacement
2) delete your github fieldtrip rep
3) delete the entire repo on your mac
4) re-fork your github repository from fieldtrip/fieldtirp
5) checkout again on your mac
6) recommit ft_electrodeplacement in the way below (which would be the 'proper' way to commit and pull request)

In your repo on your mac, do
- git checkout -b bugfixhascolor % this will create a branch in your repo, and 'checkout' this branch (make it the active one)
- copy over ft_electrodeplacement and commit
- git push origin bugfixhascolor % this will put the new branch, with only this commit in it, to your fieldtrip githubfork
- pull request from fieldtrip/fieldtrip of this branch

Then, once the pull has been accepted (!), the bloew is one of the many ways to update your fork, and your repo
First, go back to master (very important!):
- git checkout master
Then, add fieldtrip/fieldtrip as a remote:
- git remote add originmain https://github.com/fieldtrip/fieldtrip.git
Then, pull from this remote into your master, and push to your own fork master
- git pull originmain master
- git push origin master
Then, you can delete the bugfix branch if you wish
- git branch -d bugfixhascolor

**Comment by roemervandermeij** [comment]
Hmmm, I may have been freaking without reason, as the commits were likely pull request from you to update your own fork? As such, it should have been okay. But, how would we know whether nothing bad happens, when all of the commits (the merge master ones) are thousands and thousands of lines of code?

I think this is a good point for discussion, @robertoostenveld @schoffelen. The question being, how should we update our forks? The way I update my fork, using my local clone (last steps in comment above), no additional commits are created, and doing pull requests into fieldtrip/fieldtrip will result only in the commit that I want added. But it's also indirect...

What are your thoughts on this?

**Comment by StolkArjen** [comment]
Per background: this was my first pull request. Thus far all I have done,
is start with a new 'fork' a couple of months ago, and pulled in updates
from the fieldtrip master.

2016-03-10 13:54 GMT-08:00 Roemer van der Meij <notifications@github.com>:

**Pull request closed without merging**
