### PR TITLE
tetra mesh as input for simbio 

### PR DESCRIPTION
**Pull request by mcpiastra**
improve prepare_mesh_tetrahedral.m so that the tetra mesh in output can be read by ft_headmodel_simbio.m

### CODE REVIEW

**Comment by mcpiastra** [comment]
this issue was triggered by this email: https://mailman.science.ru.nl/pipermail/fieldtrip/2020-May/040021.html

**Comment by mcpiastra** [comment]
I have identified already some parts of the code to modify in order to fix this issue, how do I suggest them?

**Comment by robertoostenveld** [comment]
I ran the test script and it errors (as expected) with 

```
Error using ft_headmodel_simbio (line 65)
No element indices declared!
Error in ft_prepare_headmodel (line 467)
    headmodel = ft_headmodel_simbio(geometry, 'conductivity', cfg.conductivity); 
```

because `mesh_vol_tet` does not contain the tissue and tissuelabel field. I guess this requires changes to `prepare_mesh_tetrahedral`. 

You have the test script on your `mcpiastra:simbio_tetra_mesh` branch, which is the basis of this pull request. If you add more commits to that branch and push that branch (from your local computer to github), those commits will be automatically be added here. 

So the procedure is that you keep on working on your `mcpiastra:simbio_tetra_mesh` branch, pushing it regularly, and then once you feel that you are done you ask @schoffelen or me to review and merge. In the meantime, I will convert this PR to draft ad add the label "work in progress".

**Comment by robertoostenveld** [comment]
Oh, you might want to contact Roberto Garza and ask him to "add" himself to this pull request by writing a short comment. He will then be notified of the progress.

**Comment by mcpiastra** [comment]
I did the commits on my local branch, the git pull upstream master and the git push origin master. I cannot see commits here. What I am doing wrong?

**Comment by Spaak** [comment]
> I did the commits on my local branch, the git pull upstream master and the git push origin master. I cannot see commits here. What I am doing wrong?

I think this pushes the commits to your remote master branch and instead you need to do `git push origin simbio_tetra_mesh` (or something else, but if I recall correctly git will tell you what to do if you simply try to do `git push` (nothing else) when working on a local-only branch).

**Comment by mcpiastra** [comment]
> > I did the commits on my local branch, the git pull upstream master and the git push origin master. I cannot see commits here. What I am doing wrong?
> 
> I think this pushes the commits to your remote master branch and instead you need to do `git push origin simbio_tetra_mesh` (or something else, but if I recall correctly git will tell you what to do if you simply try to do `git push` (nothing else) when working on a local-only branch).

thank you! yes!

**Comment by robertoostenveld** [comment]
is it ready for review? If so, please click on the "ready for review" button? That will change remove the "draft" state and also allows me to merge (which is currently not yet possible).

**Pull request closed without merging**
