### PR TITLE
implemented neighbcorr method for summary mode in rejectvisual

### PR DESCRIPTION
**Pull request by robertoostenveld**
this computes for every channel in every trial the squared correlation (R2) with the neighbouring channels. If the squared correlation is low, the channel has a timecourse that is very different from its neighbours, potentially indicating an artifact.

You can test this with

```
%%

cfg = [];
cfg.dataset = 'Subject01.ds';
cfg.channel = 'all';
% cfg.channel = 'MEG';
cfg.demean = 'yes';
cfg.baselinewindow = [-inf inf];
data = ft_preprocessing(cfg);

%%

cfg = [];
cfg.method = 'summary';
cfg.neighbours = 'ctf151_neighb.mat';
data_clean = ft_rejectvisual(cfg, data);

```
and subsequently clicking the neighbcorr option.

image

In the test MEG dataset above there are reference channels (the first ~35) and a trigger channel (the last) that don't have neighbours and hence a value of 0. All MEG channels have a squared correlation of >0.95 with their neighbours.

### CODE REVIEW

**Comment by schoffelen** [comment]
Tja, je moet toch iets in je vrije weekend. Go for it!

**Comment by robertoostenveld** [comment]
I noticed that the axes of the plots are not correct, i.e. it projects the maxima, whereas it should project the minima (since small R^2 values are interesting). I will try to fix this.

**Comment by robertoostenveld** [comment]
I fixed the display of the smallest/negative versus the largest/positive values. Here is the same data once more, now you can see that the single-trial correlation with the neighbours is not so high after all.

Screenshot 2020-05-31 at 15 09 46

**Comment by StolkArjen** [comment]
Doet Robert nou data analyse?

**Comment by robertoostenveld** [comment]
> Doet Robert nou data analyse?

ja, en dan kom ik er wel achter dat ik wel wat stroef geworden ben 😁

**Comment by StolkArjen** [comment]
> > Doet Robert nou data analyse?
> 
> ja, en dan kom ik er wel achter dat ik wel wat stroef geworden ben 😁

Haha ja, was 't nou ft_frequencyanalysis, ft_freqanalyze, ...

**Pull request merged**
