### PR TITLE
FIX+OCTAVE: fix case where input is empty string

### PR DESCRIPTION
**Pull request by nno**
Addresses http://bugzilla.fieldtriptoolbox.org/show_bug.cgi?id=3269

### CODE REVIEW

**Comment by nno** [comment]
Note that CoSMoMVPA passes the tests again, but the issue is not resolved - I switched temporarily away from the official FT to use this branch. 

See https://github.com/CoSMoMVPA/CoSMoMVPA/pull/136

**Comment by nno** [comment]
@robertoostenveld since I would like to be able to use the official FT again, it would be great if you could have a look. Thanks.

**Comment by robertoostenveld** [comment]
sorry for the slow response. we have a project workshop and mid-term review this week, so I am very busy.

**Comment by nno** [comment]
No worries, thanks for merging.

**Pull request merged**
