### PR TITLE
FIX - fix to apply rotation only to the coil orientations

### PR DESCRIPTION
**Pull request by schoffelen**
This was reported already a long time ago, and I think the reporter is right (see bugzilla bug 3263)
@robertoostenveld can you quickly review this and merge if agreed?

### CODE REVIEW

**Comment by robertoostenveld** [comment]
The suggested change looks good to me, but I wonder how the bug affects current analyses. The translation would make the channel orientation quite random, right? Or would the effect be small due to the orientation being unit-scaled, and the translation being small (like 0.1, i.e. 10cm or so)?

**Comment by robertoostenveld** [comment]
I checked, the translation in H is not small. So it would have affected the source reconstruction results of people using the coil accuracy option (most will not use it yet).

I think it would be good to see how strong the effect is. I will ask @ualsbombe whether he can help me do a simple test with a dipole fitted to a SEF following median nerve stimulation.

**Comment by schoffelen** [comment]
I quickly created some grad structures with different coilaccuracies, and subsequently a leadfield of a dipole at a somewhat random location. Indeed the differences are appreciable, although luckily the translation is expressed in meters, and therefore not super big. What the effect is upon inversion, I am not sure.

**Comment by robertoostenveld** [comment]
ha, you beat me to it. I did more or less the same with 
```function test_pull832

% WALLTIME 00:10:00
% MEM 3gb

% TEST ft_read_sens ft_read_header mne2grad

%%

% cd(dccnpath('/home/common/matlab/fieldtrip/data/test/pull832'));

%%

filename = 'sub-01-ses-meg-meg-sub-01_ses-meg_task-facerecognition_run-01_meg.fif';

hdrx = ft_read_header(filename, 'coilaccuracy', []);
hdr0 = ft_read_header(filename, 'coilaccuracy', 0);
hdr1 = ft_read_header(filename, 'coilaccuracy', 1);
hdr2 = ft_read_header(filename, 'coilaccuracy', 2);

%%

gradx = ft_read_sens(filename, 'senstype', 'meg', 'coilaccuracy', []);
grad0 = ft_read_sens(filename, 'senstype', 'meg', 'coilaccuracy', 0);
grad1 = ft_read_sens(filename, 'senstype', 'meg', 'coilaccuracy', 1);
grad2 = ft_read_sens(filename, 'senstype', 'meg', 'coilaccuracy', 2);

if false
  % this only ran once on 12 Oct 2018 with the old code
  gradx_old = ft_read_sens(filename, 'senstype', 'meg', 'coilaccuracy', []);
  grad0_old = ft_read_sens(filename, 'senstype', 'meg', 'coilaccuracy', 0);
  grad1_old = ft_read_sens(filename, 'senstype', 'meg', 'coilaccuracy', 1);
  grad2_old = ft_read_sens(filename, 'senstype', 'meg', 'coilaccuracy', 2);
  
  save gradx_old gradx_old
  save grad0_old grad0_old
  save grad1_old grad1_old
  save grad2_old grad2_old
else
  load gradx_old
  load grad0_old
  load grad1_old
  load grad2_old
end

assert( isequal(gradx, gradx_old));
assert(~isequal(grad0, grad0_old));
assert(~isequal(grad1, grad1_old));
assert(~isequal(grad2, grad2_old));

%%

vol = [];
vol.o = [0 0 4];
vol.r = 10;
vol.unit = 'cm';

dippos = [0 0 9];
dipmom = [0 1 0]';

lfx = ft_compute_leadfield(dippos, gradx, vol) * dipmom;

%%

vol = [];
vol.o = [0 0 0.04];
vol.r = 0.10;
vol.unit = 'm';

dippos = [0 0 0.09];
dipmom = [0 1 0]';

lf0 = ft_compute_leadfield(dippos, grad0, vol) * dipmom;
lf1 = ft_compute_leadfield(dippos, grad1, vol) * dipmom;
lf2 = ft_compute_leadfield(dippos, grad2, vol) * dipmom;

%%

lf0_old = ft_compute_leadfield(dippos, grad0_old, vol) * dipmom;
lf1_old = ft_compute_leadfield(dippos, grad1_old, vol) * dipmom;
lf2_old = ft_compute_leadfield(dippos, grad2_old, vol) * dipmom;

%%

figure
ft_plot_dipole(dippos, dipmom, 'unit', 'm')
ft_plot_sens(grad0)

%%

figure
plot([lf0, lf0_old]);
hold on
plot(lf0-lf0_old, 'k');
relvar = (norm(lf0-lf0_old) ./ norm(lf0))^2

figure
plot([lf1, lf1_old]);
hold on
plot(lf1-lf1_old, 'k');
relvar = (norm(lf1-lf1_old) ./ norm(lf1))^2

figure
plot([lf2, lf2_old]);
hold on
plot(lf2-lf2_old, 'k');
relvar = (norm(lf2-lf2_old) ./ norm(lf2))^2
```

the differences before and after the fix have a relative residual variance of 0.02, i.e. 2%. It is not too dramatic and I don't expect that any neuroscientific findings would have been seriously affected.

**Comment by schoffelen** [comment]
OK, good. As a caveat, I think that the magnetometers might have been slightly more affected than the gradiometers. Not sure whether taking the sensor types together in comparing the relative difference obscures this, or not.

**Comment by robertoostenveld** [comment]
in my simulation I get this when splitting over the magnetometers and planar gradiometers 

```
>> relvar = (norm(lf0(mag)-lf0_old(mag)) ./ norm(lf0(mag)))^2
relvar =
    0.0194
>> relvar = (norm(lf0(pla)-lf0_old(pla)) ./ norm(lf0(pla)))^2
relvar =
    0.0209
```

So not much difference.

**Pull request merged**
