### PR TITLE
Melbourne Subcortical Atlas

### PR DESCRIPTION
**Pull request by neurofractal**
Implement the Melbourne Subcortical Atlas  (https://doi.org/10.1038/s41593-020-00711-6). Scale 1.

#1612

### CODE REVIEW

**Comment by neurofractal** [comment]
Some test code to show the atlas working:

```matlab
% Get the path and version of Fieldtrip
[~, r] = ft_version;

melb_sub = ft_read_atlas(fullfile(r,'template','atlas','melb_subcortical'...
    ,'melb_sub.mat'));

% Load 8mm sourcemodel
load(fullfile(r,'template','sourcemodel','standard_sourcemodel3d8mm.mat'));
sourcemodel     = ft_convert_units(sourcemodel,'mm');

% and call ft_sourceinterpolate:
cfg                         = [];
cfg.interpmethod            = 'nearest';
cfg.parameter               = 'tissue';
sourcemodel_subcortical     = ft_sourceinterpolate(cfg, melb_sub,sourcemodel);

figure;
for i = 1:16
    subplot(4,4,i);
    indx = find(sourcemodel_subcortical.tissue==i);
    ft_plot_mesh(sourcemodel.pos(sourcemodel.inside,:),'vertexsize',1); hold on;
    ft_plot_mesh(sourcemodel.pos(indx,:),'vertexcolor','r','vertexsize',20);
    title(sourcemodel_subcortical.tissuelabel{i},'interpreter','none');
    view([-270 0]);
    drawnow;
end
```

melb_cortical

**Comment by robertoostenveld** [comment]
could you add the example code to `fieldtrip/test/test_ft_read_and_plot_atlas.m`?

**Comment by neurofractal** [comment]
See above :)

**Comment by robertoostenveld** [comment]
looks good to me, so I will merge. 

Could you also add a short description of the atlas to https://github.com/fieldtrip/website/blob/master/template/atlas.md (and if you want you might also add a figure there)? That serves as a reference to external documentation, but you can also see it as a place to "advertise" the atlas, i.e. highlight what the specific qualities of the new atlas are and why people should consider using it. Just as a mat file in the fieldtrip release people are unlikely to start using it.

**Pull request merged**
