### PR TITLE
implement electrode placement for sEEG shaft and ECoG grid

### PR DESCRIPTION
**Pull request by robertoostenveld**

### CODE REVIEW

**Comment by robertoostenveld** [comment]
this still requires some review by Biao and Arjen. 

FYI, the code that I used looks like this

```
%%
% first part is specific to this dataset

mark = convert_logfile('DA00101J');

% sort them according to the 2nd column
[dum, indx] = sort([mark{:,2}]);
mark = mark(indx,:);

% the first and last one seem incomplete intervals
mark = mark(2:end-1,:);

%%
% read the data

% Nihon Kohden ASCII EEG header fields:
% -------------------------------------
% TimePoints is 1035000
% Number of Channels is 147
% BeginSweep[ms] is 0.00
% SamplingInterval[ms] is 1.00 (or 1000.0 Hz)
% Bins/uV is 1.00
% Start Time is 17:02:28
%

cfg = [];
cfg.dataset = 'DA00101J.m00';
data = ft_preprocessing(cfg);

%%
% verify that the marked segments (with begin/end) contain a signal of interest

begsample = data.fsample * [mark{1:2:end-1,2}]';
endsample = data.fsample * [mark{2:2:end,2}]';

cfg = [];
cfg.artfctdef.stimulus.artifact = [begsample(:) endsample(:)];
cfg.viewmode = 'vertical';
cfg.channel = {'C*'};
ft_databrowser(cfg, data);

%%

mri = ft_read_mri('T1_defaced.nii');

cfg = [];
cfg.clim = [0 0.5];
cfg.location = [0 0 0];
cfg.locationcoordinates = 'head';
ft_sourceplot(cfg, mri)

% note, the MRI seems to be in a RAS coordinate system
% although the y-axis is not through nasion

%%

ct = ft_read_mri('CT.nii');

% the CT 4x4 transform describes a left-handed coordinate system
% flip the volume to approximately align ijk to xyz

cfg = [];
cfg.method = 'flip';
ct_flipped = ft_volumereslice(cfg, ct);

cfg = [];
cfg.clim = [0 1];
cfg.location = [0 0 0];
cfg.locationcoordinates = 'head';
ft_sourceplot(cfg, ct_flipped)

% start with initial coregistration using landmarks determined from  ft_sourceplot

cfg = [];
cfg.method = 'fiducial';
% voxel coordinates
cfg.coordsys = 'neuromag'; % the MRI mostly resembles this
cfg.fiducial.nas    = [303 435 153];
cfg.fiducial.lpa    = [136 228 135];
cfg.fiducial.rpa    = [423 212 135];
cfg.fiducial.zpoint = [267 246 332];
ct_realigned1 = ft_volumerealign(cfg, ct_flipped);

cfg = [];
cfg.clim = [0 1];
cfg.location = [0 0 0];
cfg.locationcoordinates = 'head';
ft_sourceplot(cfg, ct_realigned1)

%%

mri.coordsys = 'neuromag';
ct_realigned1.coordsys = 'neuromag';

ft_determine_coordsys(mri, 'interactive','no');
ft_determine_coordsys(ct_realigned1, 'interactive','no');

%%
% improve on the coregistration using automatic  procedure from SPM

cfg = [];
cfg.method = 'spm';
cfg.spmversion = 'spm12';
cfg.coordsys = 'neuromag';
ct_realigned2 = ft_volumerealign(cfg, ct_realigned1, mri);

cfg = [];
cfg.clim = [0 1];
cfg.location = [0 0 0];
cfg.locationcoordinates = 'head';
ft_sourceplot(cfg, ct_realigned2)

ft_determine_coordsys(mri, 'interactive','no');
ft_determine_coordsys(ct_realigned2, 'interactive','no');

%%
% determine the name of the 11 electrode shafts

for i=1:(147-2)
  shaftname(i) = data.label{i}(1);
end
shaftname = unique(shaftname)';

disp(shaftname);

%     'C'
%     'F'
%     'H'
%     'K'
%     'L'
%     'M'
%     'O'
%     'Q'
%     'T'
%     'U'
%     'Y'

%%
% for each x in CFHKLMOQTUY, place electrode x1 at the tip and x2 somewhere along the shaft

cfg = [];
cfg.method = 'volume';
cfg.channel = data.label;
elec_tip_along = ft_electrodeplacement(cfg, ct_realigned2);

% determine the full array of electrodes for each shaft
for i=1:numel(shaftname)
  l = shaftname(i);
  
  cfg = [];
  cfg.method      = 'shaft';
  cfg.shaft.distance = 5; % the CT is in mm, so use that here as well

  cfg.channel     = ft_channelselection([l '*'], data.label);
  cfg.shaft.tip   = elec_tip_along.elecpos(strcmp([l '1'], elec_tip_along.label), :);
  cfg.shaft.along = elec_tip_along.elecpos(strcmp([l '2'], elec_tip_along.label), :);

  shaft{i} = ft_electrodeplacement(cfg);

  % these are required to make ft_appendsens happy
  shaft{i}.unit = 'mm'; 
  shaft{i}.type = 'seeg';
  
end

% combine them in one electrode array
elec = ft_appendsens([], shaft{:});

% make final figure
ft_determine_coordsys(mri, 'interactive', 'no');
ft_plot_sens(elec, 'elecshape', 'sphere', 'elecsize', 2, 'label', 'no', 'fontcolor', 'y', 'facecolor', 'w')
```

which results in the end in this figure that shows the sEEG electrodes in relation to the anatomical MRI.

screen shot 2018-11-08 at 16 59 38

**Comment by StolkArjen** [comment]
Code changes look good to me. Btw, in case it’s an easy fix for you with this function fresh in mind, we recently noticed that the surface method no longer worked well. Points clicked on the surface would occasionally ‘fall through’ the mesh and end up at another mesh point. Richard Jimenez and I initially fixed it a while ago (copy pasting large bits of the point3d function or something similarly named, forgot the pr id too), but later versions would contain the same bug again. We didn’t touch this part of the function anymore since we knew it was being developed as part of the EEG electrode placement tool

**Comment by robertoostenveld** [comment]
The problem I ran into is that the specific CT I am working on is not of sufficient resolution to identify individual electrodes along the shaft robustly. There is quite some blurring/leakage in the image, probably due to suboptimal imaging parameters. Also, a part of of the shaft is outside the head (for some of the shafts, there are 11 in total) and that part is even more blurry.

Re novelty: the idea is to specify the tip of the shaft and a point along (e.g. in the middle or at the end, not the end per see), and specify the distance between electrodes. We could extend it further to have multiple points along the shaft to deal with the bending. 

Re further ideas: on the way to work I was thinking that we could do the same for ECoG grids, i.e. have the user specify the 4 corner points and place the grid automatically in between. Like this:

```
cfg.grid.dim = [8 4]
cfg.grid.corner1 = [x1 y1 z1]
cfg.grid.corner2 = [x2 y2 z2]
cfg.grid.corner3 = [x3 y3 z3]
cfg.grid.corner4= [x4 y4 z4]
cfg.channel = list of 32 labels
```

It would have to deal with the imperfect non-rectangular specification of the corners, and with the out-of-plane twist due to specifying 4 points. Again, the result would be an approximation, and definitely should be followed by ft_electroderealign with method=project to get them on the brain surface.

**Comment by robertoostenveld** [comment]
can you file a bug/issue for the surface problem that you mentioned? Is that for the cfg.method=headshape option in ft_electrodeplacement? It might be due to the surface not being closed, i.e. gaps between triangles.

**Comment by StolkArjen** [comment]
I see, that makes sense indeed. As for your grid idea, that would be a very useful addition too. It’s been hard to localize individual electrodes in 2mm high density grids. If you think you can implement that as well, we should make a short demonstration, linked to from the human ieeg tutorial (around the elecplacement step).

Currently traveling and will submit that bug report when back. It’s likely caused by those gaps indeed. The problem is I forgot how we fixed it, but it should be in richard jimenez’s pr.

**Comment by robertoostenveld** [comment]
I will also make an example/test script that demonstrates the functionality

**Comment by StolkArjen** [comment]
Cannot try it out as I’m traveling, but code looks good to me. Nice functionality overall. If you’re planning on making an example script, please add screenshots of the elec placement process.

**Comment by raintwoto** [comment]
yes... I think it also works

**Comment by raintwoto** [comment]
For the code, I got this error message:
error  mat2file
Cant get 'fname'.
error file_array/subsasgn>subfun (line 158)
    mat2file(sobj,dat,va{:});
error file_array/subsasgn (line 85)
        subfun(sobj,double(dat),args{:});
error nifti/subsasgn>fun (line 74)
                val = subsasgn(obj.dat,subs(2:end),val);
error nifti/subsasgn (line 20)
        obji    = fun(obji,subs,val);
error volumewrite_spm (line 84)
        N.dat(:,:,:)    = data;
error ft_write_mri (line 70)
    V = volumewrite_spm(filename, dat, transform, spmversion);
error ft_volumerealign (line 978)
      V1 = ft_write_mri(tname1, mri.anatomy, 'transform', mri.transform, 'spmversion', spm('ver'),
      'dataformat', 'nifti_spm'); % source (moved) image

when I try to run:

ct_realigned2 = ft_volumerealign(cfg, ct_realigned1, mri);
 
I checked the internet and it says that it may caused by not enough power, but even after I run matlab using the administrator rights, the error is still there.

**Comment by robertoostenveld** [comment]
The error that you get seems related to the writing of a temporary file. It might be that the temporary location ("/tmp" on linux and mac, but I don't know where on windows) does not exist. I suggest you set a MATLAB breakpoint on line 978 in ft_volumerealign to see what is happening. 

Since it is not related to the present PR, I will merge and add the new code to the release.

**Comment by StolkArjen** [comment]
Thanks, Robert. Did you make an example script by any chance? No critical, but if you did, I will link it to the tutorial

**Pull request merged**
