### PR TITLE
ENH - don't deal exclusively with grad  if also an elec is present

### PR DESCRIPTION
**Pull request by schoffelen**
This PR is a placeholder to deal with an issue reported by Mikkel.

Merging this in its current state will for sure crash test_ft_componentanalysis because the data on disk will be different from the computed data, due to the handling of the sensor array information

### CODE REVIEW

**Comment by schoffelen** [comment]
this relates to issue #1260

Thinking it over, it is probably difficult to correctly deal with, because in principle a sequence of componentanalysis/rejectcomponent with updatesens is true with mixed EEG/MEG data yields grad/elec arrays with mixed in EEG/MEG data. Dealing with this correctly in the forward computation is probably not straightforward.

**Comment by schoffelen** [comment]
However, having said this, I think that it is reasonable to expect correct functional code if a mixed channel data structure is subjected to componentanalysis with cfg.channel = 'MEG' or 'EEG'

**Comment by schoffelen** [comment]
although this will end up being much more work than anticipated, I think I'd like to build in some better control (and support) for different chantypes in componentanalysis/rejectcomponent. My suggestion will be to have the same cfg option as in ft_denoise_prewhiten, cfg.split which determines how the unmixing is determined, which can be either across different channel types, or per specified channel type (where it makes sense to e.g. define cfg.split = {'MEG' 'EEG'} or perhaps also {'MEGMAG' MEGGRAD' 'EEG'} or so. The consequence of this would be that the updatesens results in internally consistent grad/elec arrays (because the off-diagonal blocks of unmixing coefficients will be zero by construction), which will not be the case when the unmixing is done across channel types. In the latter case, we could throw an error/warning if updatesens = true. @robertoostenveld @natmegsweden what do you think?

**Comment by schoffelen** [comment]
Or perhaps we should constrain ourselves here to 'senstypes' rather than 'chantypes'

**Comment by robertoostenveld** [comment]
once we are at it, I think we should do chantypes and not only senstypes. Splitting between meggrad and megmag makes sense, and consistency with ft_denoise_prewhiten would be valuable. I could imagine this being a suitable project for a hackathon session.

**Comment by schoffelen** [comment]
Most of it is now in place, the only thing left to do - for consideration - is to deal with the elec/grad. Currently, the sensor information is discarded.

**Pull request merged**
