### PR TITLE
ENH - updated test function to latest version of tutorial

### PR DESCRIPTION
**Pull request by schoffelen**
This fixes the regression error for test_tutorial_mvpa_light.

2 points to mention:

- @robertoostenveld perhaps you need to upgrade the version of mvpa-light on your end for this to run without errors
- @treder I still need to manually update the labels before plotting, because in my version (i.e. the master repo) of the code the function still creates 'combined(<blabla>)' labels when running a spatial searchlight.

### CODE REVIEW

**Comment by robertoostenveld** [comment]
I have to teach this morning, and then have a few meetings. So me testing will have to wait until later this afternoon.

**Comment by treder** [comment]
My apologies, looks like I didn't commit that last fix, it's just local. The "adapt channel labels" cell needs to be 

```
%% adapt channel labels
if any(strcmp('chan', cfg.mvpa.dimension_names(cfg.features)))
  % combine all labels when chan is used as features
  label = sprintf('combined(%s)', sprintf('%s',cfg.channel{:})); 
elseif ~isempty(cfg.neighbours)
  label = cell(size(cfg.neighbours,1), 1);
  if (size(cfg.neighbours,1) == size(cfg.neighbours,2)) && all(diag(cfg.neighbours))
    % keep label unchanged
    label = cfg.channel;
  else
    % merge neighbours into combined channels
    for ix = 1:numel(label)
      chan_ix = cfg.neighbours(ix,:);
      if sum(chan_ix)>1
        label{ix} = sprintf('combined(%s)', strjoin(cfg.channel(chan_ix), ','));
      else
        label{ix} = cfg.channel{chan_ix};
      end
    end
  end
end
```

The 'keep label unchanged' part is new. Shall I open another pull request?

**Comment by schoffelen** [comment]
If it's not a big deal, yes please. Otherwise, I just cut-and-paste.

**Comment by robertoostenveld** [comment]
It is currently running, all good so far. The tutorial test script is still running; I will report back once it is done. 

I noticed this being printed on screen:

```
stat = 

  struct with fields:

        confusion: [3x3 double]
    confusion_std: [3x3 double]
             mvpa: [1x1 struct]
            label: 'combined(MLC11MLC12MLC13MLC14MLC15MLC21MLC22MLC23MLC24MLC31MLC32MLC33MLC41MLC42MLC43MLF11MLF12MLF21MLF22MLF23MLF31MLF32MLF33MLF34MLF41MLF42MLF43MLF44MLF45MLF51MLF52MLO11MLO21MLO22MLO31MLO32MLO33MLO41MLO42MLO43MLP11MLP12MLP13MLP21MLP22MLP32MLP33MLP34MLT11MLT12MLT13MLT14MLT15MLT16MLT21MLT22MLT23MLT24MLT25MLT26MLT31MLT32MLT33MLT34MLT35MLT41MLT42MLT43MLT44MRC11MRC12MRC13MRC14MRC15MRC21MRC22MRC23MRC24MRC31MRC32MRC33MRC41MRC42MRC43MRF11MRF12MRF21MRF22MRF23MRF31MRF32MRF33MRF34MRF41MRF42MRF43MRF44MRF45MRF51MRF52MRO11MRO12MRO21MRO22MRO31MRO32MRO33MRO41MRO42MRO43MRP11MRP12MRP13MRP21MRP22MRP31MRP32MRP33MRP34MRT11MRT12MRT13MRT14MRT15MRT16MRT21MRT22MRT23MRT24MRT25MRT26MRT31MRT32MRT33MRT34MRT35MRT41MRT42MRT43MRT44MZC01MZC02MZF01MZF02MZF03MZO01MZO02MZP01MZP02)'
             time: 0.6000
           dimord: 'metric_metric'
             elec: [1x1 struct]
             grad: [1x1 struct]
              cfg: [1x1 struct]
```

I think it would be more appropriate to add comma's between the labels and suspect that them missing here is a bug.

**Comment by treder** [comment]
This was intentional but I will add the comma's now.

**Comment by robertoostenveld** [comment]
the test script finished without any other problems.

**Comment by treder** [comment]
OK I've updated `mv_statistics_mvpa` and opened another PR with the fix

**Comment by treder** [comment]
sorry `ft_statistics_mvpa` I'm spending too much time with MVPA-Light ;-)

**Comment by robertoostenveld** [comment]
> sorry `ft_statistics_mvpa` I'm spending too much time with MVPA-Light ;-)

mvpa_statistics_ft   🙃

**Pull request merged**
