### PR TITLE
allow sEEG (i.e. not ECoG but depth electrodes) to be visualized with ft_sourceplot

### PR DESCRIPTION
**Pull request by robertoostenveld**
see http://bugzilla.fieldtriptoolbox.org/show_bug.cgi?id=3275

### CODE REVIEW

**Comment by robertoostenveld** [comment]
@schoffelen this needs some discussion

**Comment by robertoostenveld** [comment]
I improved the handling of time and/or frequency in the data. For the ortho method it simply works, for all other methods it gives an explicit error. It is now possible to make a latency and/or frequency selection. See the test script, which now also works for method=cloud.

**Comment by robertoostenveld** [comment]
@smg211 and @StolkArjen, please note the changes here and check out test_bug3275.m

**Comment by schoffelen** [comment]
ouch, too late for me to have a look at it. Yet, Robert's comment above mentioned that it should be discussed, which we actually did so I lived up to the expectations..

**Comment by robertoostenveld** [comment]
I added the checks on hastime+hasfreq for all methods (except ortho), which I think was the most important outcome of the short discussion.

**Comment by robertoostenveld** [comment]
hmm, I think that this also solves the visualization of ECoG with cfg.method=surface (as needed for the MS). 

A small fix was needed

mac011> git commit ft_sourceplot.m 
[master eaf765f] ENH - pass cfg.sphereradius on to ft_sourceinterpolate, see #386
 1 file changed, 1 insertion(+), 1 deletion(-)

**Comment by robertoostenveld** [comment]
this

```cfg = [];
cfg.funparameter = 'powspctrm';
cfg.method = 'surface';
cfg.interpmethod = 'sphere_weighteddistance';
cfg.sphereradius = 30;
ft_sourceplot(cfg, hgb_blc, cortex_lh.mesh);```

now gives this 

![screen shot 2017-03-30 at 14 26 44](https://cloud.githubusercontent.com/assets/899043/24504035/e9359bde-1554-11e7-98e8-0527e2c2d55a.png)

The sphereradius=8 in the MS was too small, but 30 might be too large.  Oh, I have again been taking the wrong electrodes.

```
ft_plot_sens(elec_tal_fr);
```

![screen shot 2017-03-30 at 14 27 43](https://cloud.githubusercontent.com/assets/899043/24504076/1b7a95fe-1555-11e7-9c5b-641cc60f9956.png)

**Pull request merged**
