### PR TITLE
new: bis2fieldtrip elec conversion and vice versa

### PR DESCRIPTION
**Pull request by StolkArjen**

### CODE REVIEW

**Comment by schoffelen** [comment]
Where are these files located, and by which function(s) are they called?

**Comment by StolkArjen** [comment]
These wrapper functions rely on changes/additions to ft read and write sens proposed by sandon (smg201) in another pr. Given that transformation fields of the scans are required for correctly reading in the elec positions (localized with bioimage suite software), we decided not to molest ft read/write sens with that input but to create these wrapper functions. If not desired to have them in the main folder (there are other ft2xx functions), we could also put the code on the wiki.

**Comment by schoffelen** [comment]
shouldn't they then be in fileio/private?

I think that the ft2xxx function in main pertain to more full-fledged data, i.e. data with time courses etc.

**Comment by robertoostenveld** [comment]
I have not reviewed the final changes to ft_read_sens and ft_read_mri yet, but presume that both return the correct value for unit and coordsys (ijk is NOT a coordinate system).

**Pull request merged**
