### PR TITLE
Update crossvalidator.m

### PR DESCRIPTION
**Pull request by matsvanes**
Remove resetting of random seed: it is not optionable in this script, and the option is already available in ft_timelockstatistics.

### CODE REVIEW

**Comment by matsvanes** [comment]
Affirmative. If cfg.randomseed is specified in calling ft_timelockstatistics, the random number generator is fixed.

**Comment by schoffelen** [comment]
Perhaps could you leave a comment in the code, specifying that this is a fieldtrip-version specific change (i.e. something like: the fixing of the random seed has been removed here in the fieldtrip version, the randomseed is dealt with higher up in the code hierarchy)

**Comment by matsvanes** [comment]
Yep, that's what I did. I just _removed_ the feedback to the user that said the randomseed was fixed, because that's  not the case anymore.

**Comment by schoffelen** [comment]
Oh, sorry, then I misread.

**Pull request merged**
