### PR TITLE
OCTAVE: some changes in includes for .mex compilation

### PR DESCRIPTION
**Pull request by nno**
The following changes fix errors in Octave when trying to compile .mex files.

### CODE REVIEW

**Comment by nno** [comment]
ping @robertoostenveld, with these changes it seems I can compile most things with Octave. 
Can you please have a look at this tiny PR - and if possible also #332 and #334?

**Comment by nno** [comment]
ping @robertoostenveld, is there anything that stops you from pressing that beautiful big green button?

**Comment by robertoostenveld** [comment]
merely that there was no green button on the skiing slope ;-)

**Comment by nno** [comment]
Hope you had a good time skiing then :-)

**Pull request merged**
