### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by contsili**
This PR is related with #2300.

I have scripted 3 new functions that can be run once a year by the developers to keep up to date the dependency list of test scripts. 

- `test/private/find_dependency.m`: creates a dependency matrix for direct dependencies of test scripts.
- `test/private/update_dependency.m`: writes the dependencies acquired by `find_dependency.m` in the corresponding test script.
- `test/private/untested_functions.m`: finds FieldTrip high-level functions not tested by any test scripts.

Notes:

- `update_dependency.m` uses MATLAB function `writelines `that exists since MATLAB 2022a
- Running `untested_functions.m` it is found that 21 FieldTrip functions are not tested by any test script: 

> Untested functions:
> bis2fieldtrip              
> fieldtrip2besa             
> fieldtrip2bis              
> fieldtrip2ctf              
> fieldtrip2spss             
> ft_anonymizedata           
> ft_audiovideobrowser       
> ft_examplefunction         
> ft_geometryplot            
> ft_multiplotCC             
> ft_reproducescript         
> ft_sourcemovie             
> ft_statistics_analytic     
> ft_statistics_crossvalidate
> ft_statistics_mvpa         
> ft_statistics_stats        
> ft_wizard                  
> imotions2fieldtrip         
> loreta2fieldtrip           
> nutmeg2fieldtrip           
> spass2fieldtrip            
> Number of untested functions:
>     21

### CODE REVIEW

**Comment by contsili** [comment]
I also fixed two lines in `dccnpath` and corrected some `% DATA` dependencies

**Comment by contsili** [comment]
We can also check what _low-level_ functions are not tested by any test scripts.

**Comment by robertoostenveld** [comment]
Did you follow this suggestion?

> When outside the DCCN, please consider testing: test_dccnpath

**Comment by contsili** [comment]
> Did you follow this suggestion?
> 
> > When outside the DCCN, please consider testing: test_dccnpath

Yes, the test_dccnpath passed.

**Review by robertoostenveld — CHANGES_REQUESTED** [review]
There is one comment to the code that should be addressed. 

Furthermore, I suggest that we discuss (in person) how this is going to be named, also in relation to #2294. 

At the moment I think that it would be good to name all functions related to testing similarly, for example `ft_test_xxx`, to remove `ft_test` itself, and to make the functionality that exists under `ft_test` that is still of interest (such as "identify" and "run" available) in a non-nested fashion. I also think that all functions should be in the same directory (utilities?).

**Comment by robertoostenveld** [comment]
please put something like this in `compat/matlablt2022a` to deal with https://nl.mathworks.com/help/matlab/ref/writelines.html on older MATLAB versions:

```
function writelines(lines, filename)

assert(nargin==2); 
assert(ischar(filename));
assert(iscell(lines));

fid = fopen(filename, 'w');
if fid<0
  error('cannot open file');
end

for i=1:length(lines)
  fwrite(fid, '%s\n', lines{i});
end

fclose(fid);
```

**Comment by robertoostenveld** [comment]
did you already work on the `writelines` function for the compatibility with older MATLAB versions?

**Comment by contsili** [comment]
> did you already work on the `writelines` function for the compatibility with older MATLAB versions?

Yes, it is ready.

**Comment by contsili** [comment]
**Enhancement**
`ft_test` now works as a wrapper to three new functions. These new functions are `ft_test_find_dependency`, `ft_test_update_dependency`, `ft_test_untested_functions `and are placed inside `utilities/private`.

**Comments**
1. For now `ft_test find_dependency` does not output results to the MATLAB workspace, it only prints them in the command window. Shall we change that? Alternatively, we could explore options for improving the presentation of results within the command window. (see: `printstruct_as_table`)
2.. The new functions have a different format to the previous `ft_test ` functions. All the previous have the format [result] = ft_test_XX (varargin). Do we need to standardize the format of the new functions to maintain consistency with the previous format?

**Comment by robertoostenveld** [comment]
Let's merge this for now and then review the functionality together.

**Pull request merged**
