### PR TITLE
Fixed a typo: “asuming” should be “assuming"

### PR DESCRIPTION
**Pull request by gdemarchi**
Just a lousy typo that was hitting my face everytime I was staring at some MATLAB output. I couldn’t stand it anymore therefore I fixed it :-)

### CODE REVIEW

**Comment by schoffelen** [comment]
grazie mile :)

**Comment by gdemarchi** [comment]
[TYPO] Should i ask for another PR, it would be “Grazie miLle” :-) ?!
Not a fundamental contribution but, as usual more a leecher than a seeder
:-(
Best,,
-g

**Comment by robertoostenveld** [comment]
we could have changed it into "amusing"

sorry for the (often my fault) typo's, thanks for the contribution!

**Comment by schoffelen** [comment]
Sai che c'è un ristorante a Nijmegen, chi si chiama "Pinoccio"?

**Comment by gdemarchi** [comment]
> On 11.10.2019, at 18:22, Jan-Mathijs Schoffelen <notifications@github.com> wrote:
> 
> Sai che c'è un ristorante a Nijmegen, chi si chiama "Pinoccio"?

Ah ah … non mi stupisce, ho visto una pizzeria una volta che si chiamava “Bello pizzo” … ecco perché evito di mangiare italiano fuori dai confini nazionali ….
Complimenti per l’italiano!!!
-g

**Comment by gdemarchi** [comment]
> On 11.10.2019, at 15:47, Robert Oostenveld <notifications@github.com> wrote:
> 
> we could have changed it into "amusing"

Well, you can still write  further easter eggs … there are fun things that sometimes pop up in the Elekta software, that maybe dates back to Matti ...
Oh, wait …. I’m not talking to you anymore … traitor … last week you betrayed fieldtrip for mne-python :-) …  I’ve seen you on twitter and twitter doesn’t lie !!! 

> 
> sorry for the (often my fault) typo's, thanks for the contribution!

Typos mean that you did something, I just correct the mistakes of others :-( … I’m too lazy  to write tests for my code, that’s why I keep my broken code mostly for myself …
Best,
-g

PS: does everything that we write here show in in github? Oh, well … shame on me only then ...

**Pull request merged**
