### PR TITLE
Bugfix2203

### PR DESCRIPTION
**Pull request by roemervandermeij**
@robertoostenveld @schoffelen 
Hey both,
These commits have the purpose of setting an acceptable default for the plotting of channel labels in the databrowser with viewmode = 'vertical'. The current default is terrible, with labels quickly becoming unreadable if the number of channels exceed 30ish at full screen.

With the default in these commits labels have readable fonts, are non-overlapping, and dynamically dependent on window-size. This is done by changing the number of labels that are plotted in a rationaled manner. All previous configurable options are left intact, all previously cfg-specified scenarios should be fine. It works fine on my mac in 2012a and 2015a.

If you'd be able to give this branch a shot (not pull directly into master), I'd be much obliged. No default is perfect, but I think this captures the biggest possible audience.

The below should quickly illustrate it. If you resize the window, you'll see the amount of labels changing.
data = [];
data.label = cellstr([repmat('CHAN',[100 1]) num2str((101:200)')]);
data.trial{1} = randn(100,10000);
data.time{1} = (1:10000) ./ 1000;
cfg = [];
cfg.viewmode = 'vertical';
ft_databrowser(cfg,data)

### CODE REVIEW

**Comment by robertoostenveld** [comment]
I used this

```
nchan = 400

data = [];
for i=1:nchan
  data.label{i} = sprintf('chan%03d', i);
end
data.trial{1} = randn(nchan,10000);
data.time{1} = (1:10000) ./ 1000;
cfg = [];
cfg.viewmode = 'vertical';
ft_databrowser(cfg,data)
````

with nchan = 1 up to 400

Subselecting channel labels if there are too many is an efficient way of keeping them readable.

I am fine with the suggestion and will merge

**Comment by StolkArjen** [comment]
Haven't been following the entire discussion, but I built cfg.fontsize into
ft_databrowser a few months ago. Consequently, when calling ft_databrowser :

cfg.fontsize   = 1/numel(data_raw.label);

2016-05-12 12:53 GMT-07:00 Robert Oostenveld <notifications@github.com>:

**Comment by roemervandermeij** [comment]
Thanks Robert.

Arjen, we had that for a while, but it resulted often in labels being so tiny to no longer being readable. The current browser now by default subselects the labels to display, and keeps a fixed fontsize at 12 (although this can be lowered, resulting in more being plotted).

**Comment by robertoostenveld** [comment]
Roemer pimped it such that the font does not become unreadable with many
channels (or too large with few), but rather that it is always of an
acceptable size and that not all labels are shown if there are too many.





On 12 May 2016, at 21:56, StolkArjen <notifications@github.com> wrote:

Haven't been following the entire discussion, but I built cfg.fontsize into
ft_databrowser a few months ago. Consequently, when calling ft_databrowser :

cfg.fontsize = 1/numel(data_raw.label);

2016-05-12 12:53 GMT-07:00 Robert Oostenveld <notifications@github.com>:

**Comment by StolkArjen** [comment]
I see. Great stuff.

2016-05-12 13:10 GMT-07:00 Robert Oostenveld <notifications@github.com>:

> Roemer pimped it such that the font does not become unreadable with many
> channels (or too large with few), but rather that it is always of an
> acceptable size and that not all labels are shown if there are too many.
>
>
>
>
>

**Pull request merged**
