### PR TITLE
Weightnorm

### PR DESCRIPTION
**Pull request by schoffelen**
This branch is work in progress to clean up the code for the various beamformer implementations

### CODE REVIEW

**Comment by robertoostenveld** [comment]
ehm... gaat dit wel goed komen? 

I think that rebasing or squashing or so might help to clean this up and make it actually clear what the specific changes are. See https://blog.oddbit.com/post/2019-06-17-avoid-rebase-hell-squashing-wi/ and https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase. Note though that I am  not an expert on this, I always try to avoid situations like these.

**Comment by schoffelen** [comment]
oeps.

**Comment by schoffelen** [comment]
dat komt ervan als je 2 gedivergeerde lokale branchen met elkaar probeert te mergen denk ik.
I'll look at it.

**Comment by schoffelen** [comment]
OK, I think I just throw away this branch from github, and push a clean one. I think that one of my local copies is OK...

**Pull request closed without merging**
