### PR TITLE
FIX #1311 - implemented support for reading trial information from file

### LINKED ISSUE #1311: [ft_preprocessing] enable string as input to cfg.trl
If reproducescript is enabled, save the output cfg.trl from ft_definetrial. Make sure this can be read by ft_preprocessing.

@Spaak @schoffelen @robertoostenveld

### PR DESCRIPTION
**Pull request by robertoostenveld**

### CODE REVIEW

**Comment by robertoostenveld** [comment]
Hi @matsvanes, could you look at `test_issue1311.m` once more? It now also includes the reading for the artifact functions. 

There are still some others that need to be done, e.g. `ft_databrowser.m`.

**Comment by robertoostenveld** [comment]
these still need to be checked

- [ ] ft_audiovideobrowser.m
- [ ] ft_freqsimulation.m
- [ ] ft_headmovement.m
- [ ] ft_rejectartifact.m
- [ ] ft_timelocksimulation.m

**Comment by matsvanes** [comment]
> Hi @matsvanes, could you look at `test_issue1311.m` once more? It now also includes the reading for the artifact functions.
> 
> There are still some others that need to be done, e.g. `ft_databrowser.m`.

I checked test_issue1311.m on your personal branch and stumbled onto a few issues. See https://github.com/matsvanes/fieldtrip/tree/patch-3. Otherwise it looks good.

**Comment by robertoostenveld** [comment]
@matsvanes I think that reading cfg.trl from disk is now supported everywhere.

**Pull request merged**
