### PR TITLE
ENH - revamped code to match current state of online tutorial documen…

### PR DESCRIPTION
**Pull request by schoffelen**
…tation

### CODE REVIEW

**Comment by schoffelen** [comment]
I have ran this once with the 'save' commands uncommented, and stored the results in /home/common/matlab/fieldtrip/data/ftp etc. The old results are on /home/common/matlab/fieldtrip/data/ftp/tutorial/cluster_permutation_timelock/old

I checked most of the relevant files, and they seem consistent with the old ones. I don't have permission to remove the old files. @robertoostenveld could I ask you to do this?

This PR relates to:

https://github.com/fieldtrip/website/issues/252

and

https://github.com/fieldtrip/website/issues/203

**Comment by schoffelen** [comment]
@robertoostenveld could you also remove the 'old' directory in the eventrelatedaveraging tutorial on the ftp data section?

**Comment by robertoostenveld** [comment]
Yes, I can do that. Just to be sure, it is these two, right?

```
roboos@mentat002> find . -name old
./tutorial/cluster_permutation_timelock/old
./tutorial/eventrelatedaveraging/old
```

**Comment by schoffelen** [comment]
> Yes, I can do that. Just to be sure, it is these two, right?
> 
> ```
> roboos@mentat002> find . -name old
> ./tutorial/cluster_permutation_timelock/old
> ./tutorial/eventrelatedaveraging/old
> ```

Yes, please, and senk you.

**Pull request merged**
