### PR TITLE
Fix error when reading in blackrock header

### PR DESCRIPTION
**Pull request by jens-k**
..if data contains only one channel

### CODE REVIEW

**Comment by jens-k** [comment]
(this is unrelated to issue #607)

**Comment by schoffelen** [comment]
No worries Jens. With respect to this PR, I am not so familiar with the table-object, and in which format the openNsX outputs the header data. I wonder why this has gone unnoticed before. Are you sure that your intended fix is robust? (e.g. the old syntax might have worked for a different openNsX version/ matlab version etc.)

**Comment by jens-k** [comment]
Good point. The error occurred only with single-channel data (because then table(...) didn't receive a cell array but a character array as input, which it didn't like). Maybe no one tried single-channel data before?

I now tested the code on Matlab 2013b, 2014b, 2015b and 2016b on Linux and 2015b on Windows 7. In all of those versions the error occurred with one-channel data, in none of them with multi-channel data. The PR works for me on all of those versions.

I tested it using this code:
hdr = ft_read_header('singlechanneldata.ns2')

...and these data (20 KB):
https://www.dropbox.com/s/hjq3oginoiyp4qy/singlechanneldata.ns2?dl=0

**Comment by schoffelen** [comment]
Thanks for testing! As sure as we are sure that it doesn't break on multichannel data, I believe you on your blue eyes.

**Pull request merged**
