### PR TITLE
Selectdata

### PR DESCRIPTION
**Pull request by schoffelen**
This PR addresses issue #1334, which has been reported by @awollbrink

### CODE REVIEW

**Comment by schoffelen** [comment]
I thought I already linked it here, but there's an open bugzilla bug relating to the meta-issue at hand: http://bugzilla.fieldtriptoolbox.org/show_bug.cgi?id=2028

I think indeed it is worthwile to make ft_channelselection a bit more clever, in that it allows for key-value pairs that pre inform the function about the chantype or something like that.

Yet for now, to keep things moving forward, I think that the current PR is a good enough bandaid to roll out (given that it now at least also deals correctly with situations with both a grad and elec present in the data structure). Shall we merge this one, and follow the ft_channelselection issue up in a separate issue?

**Comment by robertoostenveld** [comment]
agreed!

**Comment by robertoostenveld** [comment]
this PR caused a regression error with `test_tutorial_multivariateanalysis`, due to ft_channelselection in that script searching for `MLO', but senstype being unknown. Consequently `findmlo` was true, but `labelmlo` was not defined (since that is only defined for senstype=ctf).

I will add a few lines to the `test_issue1342` script

**Comment by robertoostenveld** [comment]
I resolved the error, it was enough to initialize all channel lists to an empty cell-array. Note that it was not introduced by this PR, but only surfaced due to this PR.

**Pull request merged**
