### PR TITLE
 [BUG] Fix nmt_sourceplot for time-resolved source data, Part 2

### PR DESCRIPTION
**Pull request by sarangnemo**
Following up on #1743 from @britta-wstnr.
Masking was broken and now fixed; removed unneeded legacy code and dependence on getdimord.m

### CODE REVIEW

**Comment by britta-wstnr** [comment]
Hi @sarangnemo did just removing `getdimord.m` fix the masking? I don't see any changes apart form that?

**Comment by sarangnemo** [comment]
Oops, I made some extensive revisions to nmt_sourceplot.m as well, but you're right, they're missing from this commit. I'll try to push that as well by tomorrow.

**Comment by sarangnemo** [comment]
Push complete!

**Comment by schoffelen** [comment]
It would have been nice to also have some test code + data for future reference. Yet, given the hassle to get this sorted into its current state am fine for now to merge it without test stuff added. Please consider to add some test code in the future

**Pull request merged**
