### PR TITLE
enhancement - append_common appends through chan dimension with 4D di…

### PR DESCRIPTION
**Pull request by dieloz**

### CODE REVIEW

**Comment by robertoostenveld** [comment]
looks good. Is this being used or accessible by any higher level FT function?

**Comment by dieloz** [comment]
the only high level functions using append_common are the append functions (ft_appendtimelock/freq/data.m)

**Comment by robertoostenveld** [comment]
So ft_appendfreq now supports the 4D appending?

**Comment by dieloz** [comment]
I tried with my data and it worked. Didn't work for you?

**Comment by robertoostenveld** [comment]
No, I did not try; no reason to be worried. I was just wondering where this might be of use (e.g. on tutorials) and whether we now may be using a work-around, as it was not implemented yet.

**Comment by dieloz** [comment]
I realized because I was analizing an animal dataset on where I was pooling arrays of sensors of closeby areas coming from different fieldtrip structures. I can imagine this is not the most standard dataformat

**Pull request merged**
