### PR TITLE
Create ft_connectivity_plm.m

### PR DESCRIPTION
**Pull request by fabiobaselice**
The function for the PLM computation.

### CODE REVIEW

**Comment by schoffelen** [comment]
Would it be possible to make a single PR that incorporates the changes to the high level fieldtrip code (ft_connectivityanalysis), and includes this new function, as well as a test function?

**Comment by schoffelen** [comment]
I noticed as well that you have forked from schoffelen/fieldtrip, and not from fieldtrip/fieldtrip. in itself that is fine, but I could imagine that this complicates the way you can file a PR into this repository.

**Comment by fabiobaselice** [comment]
> Would it be possible to make a single PR that incorporates the changes to the high level fieldtrip code (ft_connectivityanalysis), and includes this new function, as well as a test function?

Of course I'll try to do it (I'm new to github)

**Comment by fabiobaselice** [comment]
> I noticed as well that you have forked from schoffelen/fieldtrip, and not from fieldtrip/fieldtrip. in itself that is fine, but I could imagine that this complicates the way you can file a PR into this repository.

Ok, I'll fix it. By the way, I'm doing a test function for the PLM. Where should I place it?

**Comment by robertoostenveld** [comment]
> I'm new to github

Welcome! Please do check out https://www.fieldtriptoolbox.org/development/git/, which provides a walk-through tutorial for github. And if you are not sure whether you are doing it right: feel free to play around with https://github.com/fieldtrip/playground, which is meant for that!

**Comment by schoffelen** [comment]
> > I noticed as well that you have forked from schoffelen/fieldtrip, and not from fieldtrip/fieldtrip. in itself that is fine, but I could imagine that this complicates the way you can file a PR into this repository.
> 
> Ok, I'll fix it. By the way, I'm doing a test function for the PLM. Where should I place it?

the test functions are typically stored in fieldtrip/test. We aim at them being self contained (i.e. using some dummy data that can be created on the spot, or otherwise we store a small accompanying datafile on our fileserver -> if you have some data that is needed to for the test, you can send it to us/me by e-mail (if it's small enough), or otherwise use some other means to transfer data through cyberspace.

**Comment by schoffelen** [comment]
> > Would it be possible to make a single PR that incorporates the changes to the high level fieldtrip code (ft_connectivityanalysis), and includes this new function, as well as a test function?
> 
> Of course I'll try to do it (I'm new to github)

No worries, it's not an absolute 'must', but perhaps a good exercise to get familiar with the process: I think that github is here to stay, so it never hurts to get your hands dirty. I am also still learning, and need to look up most things myself...

**Comment by fabiobaselice** [comment]
> I noticed as well that you have forked from schoffelen/fieldtrip, and not from fieldtrip/fieldtrip. in itself that is fine, but I could imagine that this complicates the way you can file a PR into this repository.

I press fork from fieldtrip/fieldtrip page, but it appears to me as schoffelen/fieldtrip. Could it be a permission problem?

**Pull request closed without merging**
